### ISSUE TITLE
Deploy Script Error in AutoUpdates [BUG]

### ISSUE THREAD

**Issue by nickjossy** [ukncsc/lme#10]
Line 275 of deploy.sh says:

sed -i 's#//Unattended-Upgrade::Automatic-Reboot-Time "02:00";Unattended-Upgrade::Automatic-Reboot-Time "02:00";#g' /etc/apt/apt.conf.d/50unattended-upgrades

I think this should be:

sed -i 's#//Unattended-Upgrade::Automatic-Reboot-Time "02:00";#Unattended-Upgrade::Automatic-Reboot-Time "02:00";#g' /etc/apt/apt.conf.d/50unattended-upgrades

**Comment by duncan-ncc** [comment]
Hi @nickjossy, Thanks for this, I have just tested this and you are correct.

**Comment by duncan-ncc** [comment]
Fixed in https://github.com/ukncsc/lme/commit/88264ddaaae27e1df7b08b7b00a62a55adda8f75

Thanks.
