### ISSUE TITLE
Problem with install - hanging at Waiting for elasticsearch stage

### ISSUE THREAD

**Issue by tangomanuk68** [ukncsc/lme#103]
Ubuntu 20.04 lts
16Gb RAM
2 CPU
200Gb disk
Running on VMware 6.7

I'ver seen previous issue relating to this and tried running before starting install -

sudo apt install --reinstall ca-certificates
sudo mkdir -p /etc/pki/tls/certs
sudo cp /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt

Log file shows (IP and FQDN changed for privacy)

[X] Updating OS software
Hit:1 http://gb.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://gb.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://gb.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[X] Installing prerequisites
Reading package lists...
Building dependency tree...
Reading state information...
net-tools is already the newest version (1.60+git20180626.aebd88e-1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Enter the IP of this Linux server: 101.101.200.50
Enter the Fully Qualified Domain Name (FQDN) of this Linux server. This needs to be resolvable from the Windows Event Collector: lme.blah.loc
[X] Configuring winlogbeat config and certificates to use 101.101.200.50 as the IP and lme.blah.loc as the DNS
This OS was detected as: ubuntu
[X] Configuring Auto Updates
Reading package lists...
Building dependency tree...
Reading state information...
unattended-upgrades is already the newest version (2.3ubuntu0.1).
unattended-upgrades set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
This script will use self signed certificates for communication and encryption. Do you want to continue with self signed certificates? ([y]es/[n]o): y
[!] Note: Depending on your OpenSSL configuration you may see an error opening a .rnd file into RNG, this will not block the installation
[X] Making root Certificate Authority
Generating RSA private key, 4096 bit long modulus (2 primes)
............................................++++
.....................................................................................................++++
e is 65537 (0x010001)
[X] Signing root CA
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = Swarm
Getting Private key
[X] Making Logstash certificate
Generating RSA private key, 4096 bit long modulus (2 primes)
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................++++
...........................................................++++
e is 65537 (0x010001)
[X] Signing logstash cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = lme.blah.loc
Getting CA Private Key
[X] Making Winlogbeat client certificate
Generating RSA private key, 4096 bit long modulus (2 primes)
..........................................................++++
...................++++
e is 65537 (0x010001)
[X] Signing wlbclient cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = wlbclient
Getting CA Private Key
[X] Making Elasticsearch certificate
Generating RSA private key, 4096 bit long modulus (2 primes)
...............................................................................................................................................................++++
..........................................................................................................................................................++++
e is 65537 (0x010001)
[X] Sign elasticsearch cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = elasticsearch
Getting CA Private Key
[X] Making Kibana certificate
Generating RSA private key, 4096 bit long modulus (2 primes)
.........................++++
.++++
e is 65537 (0x010001)
[X] Sign kibana cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = kibana
Getting CA Private Key
[X] Installing curl to get the Docker convenience script
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.5).
curl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[X] Installing Docker
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | apt-key add -qq - >/dev/null
Warning: apt-key output should not be parsed (stdout is not a terminal)
+ sh -c echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
+ [ -n  ]
+ sh -c apt-get install -y -qq --no-install-recommends docker-ce >/dev/null
+ [ -n 1 ]
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq docker-ce-rootless-extras >/dev/null
+ sh -c docker version
[X] Configuring Docker swarm
Swarm initialized: current node (qsxeiqziijgwbkqk6euesgccx) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-1qf0iye07xkvzyhfslkf24u0uy61yyo717w86urd2ny0evmul4-el2zglpj3zlrwx1syk2m4vaqd 101.101.200.50:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

[X] Adding certificates and keys to Docker
8riojz01y28huah4lv44a3z7f
1lh7u64pmwvbshnum9j0ufz7b
32g5gceltl82bfsfi85akfmh0
oes2tfqoyrmg6l166wfnqbotw
wy3dmpb7he9rww6actowp9s89
3g1c8vaxr03dcbvwmiqb4hy2l
lz4h6e5wq76sn4i42k2om0rzh
[X] Updating logstash configuration with logstash writer
vggem4q6tszd8db6dhpupfkx8
[X] Creating custom logstash conf
oytrbqesmo2rsgs36e1140u99
vm.max_map_count = 262144
Creating network lme_esnet
Creating service lme_elasticsearch
Creating service lme_kibana
Creating service lme_logstash
[X] Waiting for elasticsearch to be ready

After cancelling , running 

sudo docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

Any help would be much appreciated. 
Thanks

**Comment by duncan-ncc** [comment]
Hi, 

I would suggest trying to run ```docker stack deploy lme --compose-file /opt/lme/Chapter\ 3\ Files/docker-compose-stack-live.yml```
When it hangs on "waiting for elasticsearch to be ready" run
```sudo docker stack ps lme``` in a new window.

Hopefully the three containers will be shown then you can get the elasticsearch logs. 

You can do this with the following command
``` sudo docker service logs lme_elasticsearch --tail 200 ```

Thanks,
Duncan

**Comment by tangomanuk68** [comment]
Hi Duncan,
Thanks for the quick response.

Ran sudo docker stack deploy lme --compose-file /opt/lme/Chapter\ 3\ Files/docker-compose-stack-live.yml

Updating service lme_kibana (id: zclih8csqonf8fiow47ndg811)
image docker.elastic.co/kibana/kibana:7.11.2 could not be accessed on a registry to record
its digest. Each node will access docker.elastic.co/kibana/kibana:7.11.2 independently,
possibly leading to different nodes running different
versions of the image.

Updating service lme_logstash (id: lndr02aho98o1kwt8czkreagu)
image docker.elastic.co/logstash/logstash:7.11.2 could not be accessed on a registry to record
its digest. Each node will access docker.elastic.co/logstash/logstash:7.11.2 independently,
possibly leading to different nodes running different
versions of the image.

Updating service lme_elasticsearch (id: u5q5yizmr3oribzla1z6gs5v2)
image docker.elastic.co/elasticsearch/elasticsearch:7.11.2 could not be accessed on a registry to record
its digest. Each node will access docker.elastic.co/elasticsearch/elasticsearch:7.11.2 independently,
possibly leading to different nodes running different
versions of the image.

After sudo docker stack ps lme

ID             NAME                      IMAGE                                                  NODE       DESIRED STATE   CURRENT STATE                     ERROR                              PORTS
7ze1gsn24kj6   lme_elasticsearch.1       docker.elastic.co/elasticsearch/elasticsearch:7.11.2   LME01   Ready           Rejected less than a second ago   "No such image: docker.elastic…"   
4j8hfll4wcck    \_ lme_elasticsearch.1   docker.elastic.co/elasticsearch/elasticsearch:7.11.2   LME01   Shutdown        Rejected 5 seconds ago            "No such image: docker.elastic…"   
umevurj7bzj6    \_ lme_elasticsearch.1   docker.elastic.co/elasticsearch/elasticsearch:7.11.2   LME01   Shutdown        Rejected 10 seconds ago           "No such image: docker.elastic…"   
n11xxrnoz9qj    \_ lme_elasticsearch.1   docker.elastic.co/elasticsearch/elasticsearch:7.11.2   LME01   Shutdown        Rejected 15 seconds ago           "No such image: docker.elastic…"   
ysz4wcwhb846    \_ lme_elasticsearch.1   docker.elastic.co/elasticsearch/elasticsearch:7.11.2   LME01   Shutdown        Rejected 20 seconds ago           "No such image: docker.elastic…"   
i0z0ufdck756   lme_kibana.1              docker.elastic.co/kibana/kibana:7.11.2                 LME01   Ready           Rejected less than a second ago   "No such image: docker.elastic…"   
p3wdd6p8q1o9    \_ lme_kibana.1          docker.elastic.co/kibana/kibana:7.11.2                 LME01   Shutdown        Rejected 5 seconds ago            "No such image: docker.elastic…"   
db5s4dieegc6    \_ lme_kibana.1          docker.elastic.co/kibana/kibana:7.11.2                 LME01   Shutdown        Rejected 10 seconds ago           "No such image: docker.elastic…"   
55bq1c7p309f    \_ lme_kibana.1          docker.elastic.co/kibana/kibana:7.11.2                 LME01   Shutdown        Rejected 15 seconds ago           "No such image: docker.elastic…"   
o08dydbdyyeo    \_ lme_kibana.1          docker.elastic.co/kibana/kibana:7.11.2                 LME01   Shutdown        Rejected 20 seconds ago           "No such image: docker.elastic…"   
uh6qraecvu8c   lme_logstash.1            docker.elastic.co/logstash/logstash:7.11.2             LME01   Ready           Assigned less than a second ago                                      
tbin36uh79j2    \_ lme_logstash.1        docker.elastic.co/logstash/logstash:7.11.2             LME01   Shutdown        Rejected 5 seconds ago            "No such image: docker.elastic…"   
3cwg8mkn6jc5    \_ lme_logstash.1        docker.elastic.co/logstash/logstash:7.11.2             LME01   Shutdown        Rejected 9 seconds ago            "No such image: docker.elastic…"   
ghkeev9cpgsl    \_ lme_logstash.1        docker.elastic.co/logstash/logstash:7.11.2             LME01   Shutdown        Rejected 14 seconds ago           "No such image: docker.elastic…"   
7non82o3hgs0    \_ lme_logstash.1        docker.elastic.co/logstash/logstash:7.11.2             LME01   Shutdown        Rejected 20 seconds ago           "No such image: docker.elastic…"   

sudo docker service logs lme_elasticsearch --tail 20

returns nothing at all.

Thanks.

**Comment by duncan-ncc** [comment]
Hi,

Looks like your machine can't reach docker.elastic.co/elasticsearch/elasticsearch:7.11.2. 
Do you have a proxy in place or firewalls that would otherwise stop the box calling out to the internet? 


Thanks,
Duncan

**Comment by tangomanuk68** [comment]
Hi Duncan,

Yes there is a proxy. I've set up the /etc/systemd/system/docker.service.d/http-proxy.conf as per the instructions.
Is there any way I can test to make sure one way or another ?

If not I'll enquire in the morning about getting it put onto proxy bypass for the period of installation.

Thanks

**Comment by tangomanuk68** [comment]
Hi Duncan,

Stuck the server on proxy bypass and it installed perfectly fine.
Thanks for your help.

Cheers
