### ISSUE TITLE
[FeatureRequest] /r/LME

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#104]
Hi there, apologies if this isn't the proper channel, but I couldn't find a better way of contacting the dev team.

I've recently taken over the subreddit /r/LME and repurposed it as a community resource for users of LME. Though there's not a lot there yet, please come check it out. Maybe add a link to the sub in the README.  Or add some content on the sub that maybe doesn't make sense on the github.

[www.reddit.com/r/LME](https://www.reddit.com/r/LME)

**Comment by duncan-ncc** [comment]
Closed due to project archive
