### ISSUE TITLE
[FeatureRequest] Stack monitoring via metricbeat

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#105]
It would be nice if some method for gathering metrics about the stack and monitoring its performance were included. Would certainly facilitate troubleshooting. Metricbeat provides an easy way to do this that integrates nicely with the existing setup.

It should also be fairly easy to include as part of the deploy script process. Adding metricbeat logging to the existing deployment only takes (roughly) the following steps:

1. Install metricbeat on ELK host
2. metricbeat modules enable elasticsearch
3. Configure /etc/metricbeat/modules/elasticsearch.yml with information pointing to elasticsearch container and user/password information (which is known by deploy.sh)
4. Configure /etc/metricbeat/metricbeat.yml with output information to the local elasticsearch or logstash (which is known by deploy.sh)
5. (May not be necessary) Visit kibana->Stack monitoing to enable montiroing of elasticsearch node
6. Profit!

**Comment by duncan-ncc** [comment]
Closed due to project archive
