### ISSUE TITLE
lme_wec_config.xml Invalid config file. Error = 0x80070057

### ISSUE THREAD

**Issue by ByteMe64** [ukncsc/lme#106]
Hi,

Just i've just started setting up LME and instantly run into an issue I can find an answer to.  When trying to import the config on our WEC server I get the following error.

c:\>wecutil cs lme_wec_config.xml
Invalid config file. Error = 0x80070057.
The parameter is incorrect.

Server 2019, 1809, OS build 17763.1999

**Comment by duncan-ncc** [comment]
Hello, 

if you open the lme_wec_config.xml file in notepad (or similar) does it look the same as the one in the link below?
[lme_wec_config.xml](https://raw.githubusercontent.com/ukncsc/lme/master/Chapter%201%20Files/lme_wec_config.xml)


Regards,
Duncan

**Comment by ByteMe64** [comment]
Hi Duncan,

I should have checked that, no it doesn't.  I manually updated the file and all is working now, thanks for the quick reply.

Regards,
Paul.
