### ISSUE TITLE
Change Log storage location

### ISSUE THREAD

**Issue by edmitchellVS** [ukncsc/lme#107]
HI Everyone,

I have recently installed LME and created two VHD's one for system (20 GB) and one for storage of logs and home partition (750 GB) however when I ran the script it decided to install the log storage location on the system (20GB) partition.  Doe anyone know of a way that I can point the LME solution to use the larger partition?  

Thanks in advance

**Comment by duncan-ncc** [comment]
Hi,

We do not have any formalised guides on this, however I can point you in the right direction.

The LME data is stored in a docker volume (by default in /var/lib/docker/
You can change this location by editing the daemon config file as described under "data-root" here https://docs.docker.com/engine/reference/commandline/dockerd/

thanks,

**Comment by edmitchellVS** [comment]
Hi Duncan,

Thanks for this, I had a look and I cant see the file daemon.json in /etc/docker/  Does scripted version place this file else where?  I also ran a find command to locate the file but no results.  the only file in the locaton mentioned is key.json

Thanks in advance

**Comment by edmitchellVS** [comment]
Just quickly on this, if I were to reinstall LME I am guessing I could mount /home and /var on the larger disk.  I was also looking at moving the /var to the larger disk, There is a good guide to this here https://askubuntu.com/questions/39536/how-can-i-store-var-on-a-separate-partition however I believe I will need to boot to a utility disk to be able to edit locations and copy data.  Do you think this would be a good way to go?  There is also the option to install a partition tool like GParted on the GUI however i would need to enable the GUI option first and then remove once completed.  Your thoughts would be much appreciated

Thanks again
Ed

**Comment by edmitchellVS** [comment]
Hi Duncan,

We ran the fix last night and the mounting of /VAR on the other disk seems to have worked.  Not sure if this is something that may be of use to you but if you want the process let me know and I will send on.  We don seem to have lost any data either which is a bonus.

Cheers

Ed

**Comment by adam-ncc** [comment]
Hey Ed,

Thanks for the offer, we're always happy to have community contribution so feel free to expand on this here or submit a pull request with the relevant documentation and we'll look at adding it. Mounting /var on another disk might not technically be part of a typical LME process but it's useful to have the option recorded in-case other users want to pursue this same option.

I'm closing the issue for now since it doesn't seem like it's a problem for you anymore, glad to know that everything seems to be working now. 

Thanks
