### ISSUE TITLE
[FeatureRequest] Logstash Syslog listening on UDP as well as TCP

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#109]
**Is your feature request related to a problem? Please describe.**
Some network devices only support syslog over UDP or TCP+TLS. Current LME config only supports TCP sans TLS.

**Describe the solution you'd like**
Allow the logstash container to listen on UDP as well.

**Describe alternatives you've considered**
Using netcat or similar to pump traffic from UDP to TCP
Use log forwarding with rsyslog
(Both are obviously dumb and kludgey)

Easy fix: add "12514:12514/udp" to the docker-compose-stack file, under logstash->ports

**Comment by a-d-a-m-b** [comment]
This would be a great enhancement change for a PR. We can include this as part of the next release if you're happy to wait. 

thanks! :)

**Comment by tfriesen** [comment]
Alas, my git-fu is weak and whenever someone talks about 'forking' or 'pull requests' my eyes glaze over and fear grips my heart.

But I made the change on my own stack, and a quick re-run of docker stack deploy affects the change without restarting the core VMs.

Otherwise I am most content to wait.

**Comment by duncan-ncc** [comment]
Closed due to project archive
