### ISSUE TITLE
Error running "./deploy.sh update" (and files_for_windows.zip not created)

### ISSUE THREAD

**Issue by 7MinSec** [ukncsc/lme#11]
Hi there,

I'm running the `deploy.sh update` and it gets to these commands:

````
docker cp elastic_settings.sh $(docker ps -q --filter="NAME=lme_elasticsearch"):/elastic_settings.sh
docker exec -it $(docker ps -q --filter="NAME=lme_elasticsearch") bash -c "chmod +x /elastic_settings.sh"
docker exec -it $(docker ps -q --filter="NAME=lme_elasticsearch") bash -c /elastic_settings.sh
````

When the script hits the third command, I get this for an error:

````
{"acknowledged":true}/elastic_settings.sh: line 3: $'\r': command not found
````
I opened the one on my local machine and deleted the spaces between lines 2 and 3, then re-ran the commands to copy the file over and run it, and everything looks good!

I re-ran `deploy.sh update` and this time everything completed fine!  But...my *files_for_windows.zip* was not created.  I'm gonna revert the VM and try again, but not sure what the right course of action should be for a half-installed setup.  Should I have run deploy script with `install` again?

Let me know what you think!

Thanks,
Brian

**Comment by duncan-ncc** [comment]
Hi,
Thanks for your time. 

\r is a carriage return character so while this error appearing is irritating it does not break the functionality. 

The deploy.sh update function updates the Docker config, configures Elasticsearch and rebuilds the curator image. It does not regenerate user configuration files such as winlogbeat.yml, certificates or the zips.

**Comment by 7MinSec** [comment]
Hey I figured out last night that the reason my .zip was empty is I had cloned the repository to /opt/lme, and it looks like the LME wants things in ~/.  That might be something you want to clarify in the instructions?
