### ISSUE TITLE
Error: No such config: osmap.csv

### ISSUE THREAD

**Issue by LeitLei** [ukncsc/lme#119]
Every time lme_update.sh is running, I could see this error:

> Updating from git repo
> Already up to date.
> Removing existing Docker stack Removing service lme_elasticsearch Removing service lme_kibana Removing service lme_logstash Removing network lme_esnet logstash.conf logstash_custom.conf
> Attempting to remove legacy LME files (this will cause expected errors if these no longer exist)
> **Error: No such config: osmap.csv**
> Sleeping for one minute to allow Docker actions to complete...
> Updating current configuration files
> Custom logstash config exists, Not creating
> Recreating Docker stack

Can I ignore this?

**Comment by duncan-ncc** [comment]
Hello LeitLei, 

You can safely ignore that message, as the line above the error in your logs states, the subsequent command is attempting to remove a legacy configuration file from the docker engine. 

Thanks,
Duncan

**Comment by LeitLei** [comment]
Thanks for clarification!
