### ISSUE TITLE
Updated Kibana Dashboards not Working[BUG]

### ISSUE THREAD

**Issue by nickjossy** [ukncsc/lme#12]
When the Dashboard 0.1.2 was exported did you forget to include the visualisations by any chance as it is missing them (it only contains 18 objects whereas 0.1.1b contained 47).  

Also when I click on the Discover tab I get an error.  This appears to be caused by two new Scripted fields in the Winlogbeat index.  Both of these refer to separate fields that do not exist; event_data.FileVersion.keyword and event_id.  Full error message example is below.

If I delete both of these scripted fields from the Index then I can see the log data in the Discover tab, but the dashboard refers to visualisations that do not exist:-)

########

Error with Painless scripted field 'if (doc['event_data.FileVersion.keyword'].value == "10.0.17134.466 (WinBuild.160101.0800)") {return "Win10 V1803"} else if (doc['event_data.FileVersion.keyword'].value == "10.0.16299.15 (WinBuild.160101.0800)") {return "Win10 V1709"} else if (doc['event_data.FileVersion.keyword'].value == "10.0.15063.0 (WinBuild.160101.0800)") {return "Win10 V1703"} else {return "Unknown"} '
You can address this error by editing the ‘if (doc['event_data.FileVersion.keyword'].value == "10.0.17134.466 (WinBuild.160101.0800)") {return "Win10 V1803"} else if (doc['event_data.FileVersion.keyword'].value == "10.0.16299.15 (WinBuild.160101.0800)") {return "Win10 V1709"} else if (doc['event_data.FileVersion.keyword'].value == "10.0.15063.0 (WinBuild.160101.0800)") {return "Win10 V1703"} else {return "Unknown"} ’ field in Management > Index Patterns, under the “Scripted fields” tab.

Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"script_exception","reason":"runtime error","script_stack":["org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:81)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)","if (doc['event_data.FileVersion.keyword'].value == \"10.0.17134.466 (WinBuild.160101.0800)\") {","        ^---- HERE"],"script":"if (doc['event_data.FileVersion.keyword'].value == \"10.0.17134.466 (WinBuild.160101.0800)\") {return \"Win10 V1803\"} \nelse if (doc['event_data.FileVersion.keyword'].value == \"10.0.16299.15 (WinBuild.160101.0800)\") {return \"Win10 V1709\"} \nelse if (doc['event_data.FileVersion.keyword'].value == \"10.0.15063.0 (WinBuild.160101.0800)\") {return \"Win10 V1703\"} \nelse {return \"Unknown\"}\n\n\n","lang":"painless"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"fetch","grouped":true,"failed_shards":[{"shard":0,"index":"winlogbeat-02.05.2019","node":"Tj4-1V8oQlaVg5S8sBFN-g","reason":{"type":"script_exception","reason":"runtime error","script_stack":["org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:81)","org.elasticsearch.search.lookup.LeafDocLookup.get(LeafDocLookup.java:39)","if (doc['event_data.FileVersion.keyword'].value == \"10.0.17134.466 (WinBuild.160101.0800)\") {","        ^---- HERE"],"script":"if (doc['event_data.FileVersion.keyword'].value == \"10.0.17134.466 (WinBuild.160101.0800)\") {return \"Win10 V1803\"} \nelse if (doc['event_data.FileVersion.keyword'].value == \"10.0.16299.15 (WinBuild.160101.0800)\") {return \"Win10 V1709\"} \nelse if (doc['event_data.FileVersion.keyword'].value == \"10.0.15063.0 (WinBuild.160101.0800)\") {return \"Win10 V1703\"} \nelse {return \"Unknown\"}\n\n\n","lang":"painless","caused_by":{"type":"illegal_argument_exception","reason":"No field found for [event_data.FileVersion.keyword] in mapping with types []"}}}]},"status":500}

**Comment by duncan-ncc** [comment]
Hi,

You are indeed correct, It appears as only the active selection was exported. I will correct this now.
