### ISSUE TITLE
How to install LME updates in general / this time Elastic 7.16.1 ?

### ISSUE THREAD

**Issue by eisback** [ukncsc/lme#122]
Hi, sorry for this probably very simple question (I am from the Windows world) I am using Ubuntu 18.04 ... how do I install the latest updates for LME 0.4? Thanks!

**Comment by joncojonathan** [comment]
Hi @eisback.  Does this document help?: https://github.com/ukncsc/lme/blob/master/docs/upgrading.md

**Comment by adam-ncc** [comment]
Hi @eisback, just wondering if you had any update on this and whether the relevant upgrade documentation kindly linked by @joncojonathan solved your issue?

If you're already on LME v0.4 (either by upgrading an old installer, or performing a fresh install after this was released) then updates will be applied automatically if you enabled this option as part of the upgrade/install process.

If you didn't enable these and want to do a manual update then calling the deploy script as follows will perform the same function:

```
sudo /opt/lme/Chapter\ 3\ Files/deploy.sh update
```

**Comment by eisback** [comment]
Hi, thank you! I started with v.0.4 and you are right, the update was applied automatically which is very useful!
