### ISSUE TITLE
[BUG] Backups: "failed to create repository" on LME 0.4

### ISSUE THREAD

**Issue by joncojonathan** [ukncsc/lme#129]
On LME 0.4, when attempting to [create a backup repository](https://github.com/ukncsc/lme/blob/master/docs/backups.md), Kibana advises:

```
Cannot register new repository
[LME-Backups] failed to create repository
```

Inspecting the response further via web developer tools shows the request to create the repository results in an HTTP 500.  The response says:

```
{"statusCode":500,
 "error":"Internal Server Error",
 "message":"[LME-Backups] failed to create repository",
 "attributes":
    {"error":
        {"root_cause":
            [{"type":"repository_exception","reason":"[LME-Backups] location [/opt/lme/backups/] doesn't match any of the locations specified by path.repo"}],
            "type":"repository_exception",
            "reason":"[LME-Backups] failed to create repository",
            "caused_by":
                {"type":"repository_exception",
                    "reason":"[LME-Backups] location [/opt/lme/backups/] doesn't match any of the locations specified by path.repo"}},
                    "causes":["[LME-Backups] location [/opt/lme/backups/] doesn't match any of the locations specified by path.repo"]}}
```

The salient point seems to be
> location [`/opt/lme/backups/`] doesn't match any of the locations specified by `path.repo`

I'm unsure where to set `path.repo`, and potentially that'd get overwritten by an LME upgrade.  Can you advise please?

**To Reproduce**
Steps to reproduce the behavior ([following instructions](https://github.com/ukncsc/lme/blob/master/docs/backups.md)):
1. Go to Menu > _Stack Management_
2. Pick _Snapshot and Restore_
3. As this is the first repository, click _Register a repository_
4. For _Repository name_ specify `LME-Backups`
5. Click _Shared file system_ then _Next_
6. In the _Location_ box specify `/opt/lme/backups`
7. Click _Register_
8. Notice error

**Expected behavior**
Repository should be created.

**Linux Server:**
 - Docker: 20.10.12, build e91ed57
 - Docker compose stack file version: *I'm unsure how to identify this, sorry*
 - Linux: Ubuntu 20.04.3 LTS
 - Logstash Version: 0.4 - 24/03/21

**Comment by adam-ncc** [comment]
Thanks for raising this @joncojonathan, we were able to recreate this and spotted a flaw in our backup instructions that has now been rectified as part of #134. The latest version of the instructions should hopefully resolve the issue, and I'll leave this issue open for a little while before closing it in-case you are happy to try again and report back if this worked for you.

**Comment by joncojonathan** [comment]
Hi @adam-ncc, that's looking good to me and I've been able to create the backup location.  Many thanks.
