### ISSUE TITLE
[BUG] When I run the script to install database i do not get the Kibana/Elasticsearch Credentials

### ISSUE THREAD

**Issue by dalkangh** [ukncsc/lme#130]
**Describe the issue**
A clear and concise description of what the issue is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Windows Event Collector (please complete the following information):**
 - OS: [e.g. Server 2016 v1607]
 - WEC Config [e.g. V0.1]
 - Winlogbeat Config [e.g. V0.1]
 - Winlogbeat.exe version [e.g. winlogbeat version 6.4.2 (386)]
 - sysmon config [e.g. File hash or Version]
 - sysmon executable [e.g. V8.1]

**Linux Server (please complete the following information):**
 - Docker: [e.g. Docker version 18.09.3]
 - Docker compose stack file version: [e.g. version 0.1]
 - Linux: [e.g. PRETTY_NAME="Ubuntu 18.04.2 LTS"]
 - Logstash Version [e.g. #LME logstash config V0.1]

**Additional context**

**Comment by adam-ncc** [comment]
Hey @dalkangh, would you be able to include some additional information on what you observed during the install apart from a lack of credentials? I'm struggling to reproduce this error so any more information would be helpful, in particular whether any errors occurred during the install that you could share, and whether the docker stack was successfully running at the end just without outputting credentials (you can work that out with the following command:

```
sudo docker stack ps lme
```

I'd also be curious if simply uninstalling and re-installing LME stack fixes this, or whether you are missing credentials every time you run the installer?

```
sudo /opt/lme/Chapter\ 3\ Files/deploy.sh uninstall
sudo /opt/lme/Chapter\ 3\ Files/deploy.sh install
```

Thanks

**Comment by dalkangh** [comment]
Hi

Reinstalling I noticed this error:
LME Requires 8GB of RAM Available for use - exiting

Didn't notice it first time round.

I have increased RAM on the VM and script has worked.

Thanks for your help

Dal

**Comment by adam-ncc** [comment]
Glad to hear your issue was resolved, thanks.
