### ISSUE TITLE
[FeatureRequest] E-Mail Notification

### ISSUE THREAD

**Issue by eisback** [ukncsc/lme#133]
How can I realize any type of alertig via E-Mail or maybe PRTG (https://www.paessler.com)?

**Comment by edmitchellVS** [comment]
These are paid for features and I believe you need a minimum Gold level for Email/Teams etc

**Comment by eisback** [comment]
Thanks. This sounds expensive ... I just found this approach:

https://github.com/Yelp/elastalert

Has anyone already used this with LME?

**Comment by edmitchellVS** [comment]
No but it does look interesting.. I may look into this if I get chance (current climate an all)

**Comment by eisback** [comment]
The new project for alerting is called elastalert2:

https://github.com/jertel/elastalert2

Would be really a huge enhancement if something like this could be integrated in version 0.5. By the way: is LME still under active development? Thanks!

**Comment by duncan-ncc** [comment]
Hello @eisback, 
Alerting and enterprise security are two items on our roadmap and LME is under active development.

Thanks

**Comment by duncan-ncc** [comment]
Closed due to project archive
