### ISSUE TITLE
Import STIX file or stream [FeatureRequest]

### ISSUE THREAD

**Issue by edmitchellVS** [ukncsc/lme#135]
**Is your feature request related to a problem? Please describe.**
Multiple IOC's provided by various third party organisations require manual work to pull out required OIC's (IP's, file hashes etc) 

**Describe the solution you'd like**
It would be great if we could utilise the STIX format in LME to introduce IOC's provided by say CISA for example.

**Describe alternatives you've considered**
Only manually pull out the data which is not really feasible when there are hundreds of items.

**Additional context**
For example the STIX file provided by CISA relating to the current threat situation due to the Russian/Ukrainian situation would be very useful. For example https://www.cisa.gov/uscert/sites/default/files/publications/AR21-013A.stix.xml

**Comment by duncan-ncc** [comment]
Closed due to project archive
