### ISSUE TITLE
Kibana server is not ready yet

### ISSUE THREAD

**Issue by incodia-ash** [ukncsc/lme#137]
Hi All,

Appreciate there's another issue open of the same message, but figured a different issue raising just to get the best support.

After resolving the certificate issue before (thanks for that btw!)

The LME server has seemingly at random stopped connecting via URL, any attempts to connect to it give the "Kibana server is not ready yet" error message.

Happy to provide logs and such if someone could point me in the right direction.

Nothing has happened on the LME VM that would've changed this so curious.

Ash

**Comment by divadiow** [comment]
Ash!

did you get anywhere?

**Comment by incodia-ash** [comment]
I haven't made any progress, unfortunately... I had this happen before I got it all sorted, but my solution was to reset the entire VM and install again but, I can't keep doing that realistically.

So I'm still without the LME portal.

Any support from the LME team would be appreciated! :)

**Comment by divadiow** [comment]
was hoping to not have to go down that route. 

the command line shows the total size to be 49GB, whereas the partition is 99GB when looking at gparted. so not sure how it's all being split up or how to expand it

![image](https://user-images.githubusercontent.com/62958974/164214280-5e704972-9670-40b9-8bea-1d90f2b4b4e3.png)
![image](https://user-images.githubusercontent.com/62958974/164214321-9a467229-c1e9-49ae-a4f3-95f02d9306e0.png)

**Comment by divadiow** [comment]
OK done it :)

resized the 49GB jobbie using these instructions

https://askubuntu.com/questions/1106795/ubuntu-server-18-04-lvm-out-of-space-with-improper-default-partitioning
![image](https://user-images.githubusercontent.com/62958974/164219471-07b38c1d-1b4e-4eae-b8d0-7b8c003f9dd1.png)

**Comment by incodia-ash** [comment]
I assumed it might be a storage space issue. Have doubled my space, and after a restart it appears to let me log back in with data still there.

Awesome, thanks for your help - that page worked flawlessly @divadiow 

I'll continue to monitor and report back if there are further issues.

I guess for the sake of the LME team, perhaps the suggested storage amount should be increased during the setup process documentation? It seems like the specified amount might be hitting a snag and causing an issue with the docker suite?

**Comment by adam-ncc** [comment]
Hi both, good job on fixing the error here, I'm assuming it was just down to the lack of available disk space as you've said - it's hard to know for certain without more information but as this has solved the issue it feels like a safe bet.

I'll close this issue for now, but the need to specify and enforce a minimum disk space is a good shout and something we're already actively investigating for the next release. Thanks!
