### ISSUE TITLE
TLS 1.1

### ISSUE THREAD

**Issue by NDCDarren** [ukncsc/lme#138]
Hi All,

A recent health check has reported that our Elastic server is using TLS v1.1.

Does anyone know how to disable this and enforce TLS 1.2 / 1.3?

**Comment by adam-ncc** [comment]
Hey @NDCDarren - this can be set in the docker compose file docker-compose-stack.yml using xpack.security.http.ssl.supported_protocols and server.ssl.supportedProtocols for Elasticsearch and Kibana respectively, as documented here:

* https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#ssl-tls-settings
* https://www.elastic.co/guide/en/kibana/current/settings.html

**However**, modifying this file is **not** supported if you have automatic LME updates enabled and is likely to break things as there will be version conflicts between your local file and the latest version on the LME git repo, so is not advised at the moment.

We'll likely look to remove TLSv1.1 support in the next release provided we don't see any compatibility issues with existing users and provided Elastic don't do it by default before we get there, if you can wait for this.

Thanks for flagging this.

**Comment by adam-ncc** [comment]
An update to this @NDCDarren - we've pushed a small update now that removes TLSv1.1 support from both Elasticsearch and Kibana, as well as updating from 7.17.4 to 7.17.5 - hopefully this resolves the issue for you in the next few days if you have automatic updates enabled, or you can copy the changes we've made if you do not. You can review it here #142 .

I'll leave this issue open for a few days before closing it in-case you still have any problems, please let us know how you get on if you get a chance to check.

Thanks.

**Comment by NDCDarren** [comment]
Hi @adam-ncc,

I've just forced the update through and rescanned our server. The update has worked a treat, only TLS 1.2 is being reported across all ports.

Thanks for the help, it's much appreciated.

**Comment by adam-ncc** [comment]
Perfect, glad to hear this solved it for you.
