### ISSUE TITLE
Kibana server not ready yet?[BUG]

### ISSUE THREAD

**Issue by imran196** [ukncsc/lme#141]
Hello, 

I got an error saying kibana server not ready yet, i thought it may be because of not enough free space but the server has 90gb free, i expanded the storage anyway but it still stays the same after a restart. 
how can I start the services again? as the services say shutdown and failed to start? 

Thanks

**Comment by adam-ncc** [comment]
Hey @imran196 - there are a number of possible reasons why Kibana could be failing to start, and we'll need a little bit more information to get to the bottom of what might be causing it. 

Firstly on the Linux server type ```sudo docker stack ps lme```, and check that lme_logstash, lme_kibana and lme_elasticsearch all have a current status of running and let us know the result. 

If Kibana looks like it's failing to restart repeatedly or is hanging then it would be useful if you could gather some logs from it using the following, and then post them here with any sensitive information such as hostnames redacted:

```
sudo docker service logs lme_kibana --tail 20 --timestamps
sudo docker service logs lme_elasticsearch --tail 20 --timestamps
```

If there's nothing obviously indicating the error in those logs then you may need to expand the windows to see the problem, by increasing the number after the --tail command.

Thanks.

**Comment by imran196** [comment]
Thanks Adam, 
we did try the commands and check the logs but we had to resort to rebuilding the server from scratch. we used the latest ubuntu with the same commands and it all worked fine. 
what could have caused the issue? we have changed the log retention to 30 days instead of the 180 days so not to fill up the server.

**Comment by duncan-ncc** [comment]
Without providing logs or any errors shown we are unable to suggest what might have caused the issue.

Thanks,
Duncan

**Comment by duncan-ncc** [comment]
Closed as instance was rebuilt so no further investigation possible
