### ISSUE TITLE
Kibana server not ready yet then dead web console.

### ISSUE THREAD

**Issue by divadiow** [ukncsc/lme#143]
As I've done several times before, I expanded /dev/mapper/ubuntu--vg-ubuntu--lv by another 100GB using the methods outlined here
https://askubuntu.com/questions/1106795/ubuntu-server-18-04-lvm-out-of-space-with-improper-default-partitioning

This time, though, it appears Kibana is failing to come up. 
![image](https://user-images.githubusercontent.com/62958974/182602914-edd1c65b-c6c9-4890-9ae9-35e5c6426a36.png)

I ran 

```
cd /opt/lme/Chapter\ 3\ Files/
sudo ./deploy.sh update
```
and 
```
cd /opt/lme/
sudo ./dashboard_update.sh
```
but this hasnt helped. 
![image](https://user-images.githubusercontent.com/62958974/182603817-58c045e9-525c-44a2-9f1d-6fbe92b16009.png)

I attach logs for

```
sudo docker service logs lme_kibana --tail 20 --timestamps

sudo docker service logs lme_elasticsearch --tail 20 --timestamps
```
[LME_KIBANA.LOG](https://github.com/ukncsc/lme/files/9251157/LME_KIBANA.LOG)
[LME_ELASTICSEARCH.LOG](https://github.com/ukncsc/lme/files/9251158/LME_ELASTICSEARCH.LOG)
help!

**Comment by divadiow** [comment]
containers restarted in order as mentioned in #140 

```
 sudo docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED              STATUS              PORTS                NAMES
ec55841a94bc   docker.elastic.co/kibana/kibana:7.17.5                 "/bin/tini -- /bin/b…"   About a minute ago   Up About a minute   5601/tcp             lme_kibana.1.tu47rhksqq73a8h8k5ijjy8xd
237128929a2b   docker.elastic.co/elasticsearch/elasticsearch:7.17.5   "/bin/tini -- /usr/l…"   2 minutes ago        Up About a minute   9200/tcp, 9300/tcp   lme_elasticsearch.1.z30awe8t38zmn2kkvt8b3gjtw
f2884cc1e368   docker.elastic.co/logstash/logstash:7.17.5             "/usr/local/bin/dock…"   3 minutes ago        Up 3 minutes        5044/tcp, 9600/tcp   lme_logstash.1.wriqi4sh32kr9qgkqtiahpqvy
35dcb798f4ce   docker.elastic.co/logstash/logstash:7.17.5             "/usr/local/bin/dock…"   35 minutes ago       Up 2 minutes        5044/tcp, 9600/tcp   lme_logstash.1.83qyjape4gxc7vzk30sk8gu9v
```
kibana one is never up for long

**Comment by edmitchellVS** [comment]
OK so I had a quick look at your logs and it seems you have too many shards.  You may have two issues, too many shards and possibly a corrupted .kibana shard. First you need to fix the unassigned / corrupted .kibana shard to Kibana working then you need to have a look at https://github.com/ukncsc/lme/blob/master/docs/retention.md to fix the retention issue which will stop data from being added to elastic.

Validation Failed: 1: this action would add [2] shards, but this cluster currently has [1000]/[1000] maximum normal shards open;,"}

I had the exact same issue a while back, https://github.com/ukncsc/lme/issues/132 you need to change your retention time for the shards... see below from my earlier experience.

__":response=>{"index"=>{"_index"=>"winlogbeat-09.03.2022", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"validation_exception", "reason"=>"Validation Failed: 1: this action would add [4] shards, but this cluster currently has [1000]/[1000] maximum normal shards open;"}}}}_

_I have changed the data retention to 180 days and this now seems to have fixed the issue... May many many thanks for this!"__

Hope this helps... good luck!

**Comment by adam-ncc** [comment]
Hi @divadiow - from a look at the Kibana logs it looks like you've run out of available shards, which default to 1000 per cluster within Elasticsearch.

This is something we're looking to address in a future update by making use of shards more efficiently and shriking existing indices to use less shards as they age, but for now you can see the instructions in #60 for increasing your shard limit above the 1000 default which should get you going again.

Once you've done this it's probably worth changing the data retention settings inside the ```lme_ilm_policy``` within ```Stack Management``` -> ```Index Lifecycle Policies``` to ensure that the Delete phase is no more than 1/4 of the total number of shards you configured, so that you don't max out the shard count again in the future as currently LME uses four shards a day for indices - for example for a shard count of 1200 you would want to make sure data was deleted after less than 300 days, at the latest.

![image](https://user-images.githubusercontent.com/52567990/182646618-66dbcb10-bdc4-4c7d-b5b2-fcc060773bf1.png)

**Comment by divadiow** [comment]
ok. thank you @edmitchellVS and @adam-ncc 

I was able to increase the shard limit using this command:

`sudo curl -u elastic:<elasticuserpassword> -k -X PUT "HTTPS://127.0.0.1:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d' { "persistent": { "cluster.max_shards_per_node": "2000" } } '`

a single reboot later and we're back online. shards are new to me, so now I know! increasing the main storage space was obviously not enough. we'll review retention policies

**Comment by adam-ncc** [comment]
Glad to hear this worked for you, and thanks to @edmitchellVS for beating me to the solution there! Hopefully changing the retention settings should prevent you having any further issues with this for now, and as I mentioned previously this is something we're hoping to resolve longer term in the next release.

Thanks, Adam
