### ISSUE TITLE
[FeatureRequest]

### ISSUE THREAD

**Issue by imran196** [ukncsc/lme#145]
Hello, 

is there a way to import windows event logs manually to LME for it to analyze? issue is if we have an archived windows event log which was not picked up by lme (historic before LME or during a server crash) we would want to analyze that log file manually with LME

Thanks

**Comment by duncan-ncc** [comment]
Hello, This feels more like a support request rather than a feature request. 
However, Winlogbeat supports reading from historical event log files directly. 
https://www.elastic.co/guide/en/beats/winlogbeat/current/reading-from-evtx.html

Thanks,
Duncan

**Comment by imran196** [comment]
Thanks Duncan, that worked a treat

just for anyone reading dont use the command output.elasticsearch.hosts: ['http://localhost:9200'] 

copy the output.logstash from the current winlogbeat.yml
