### ISSUE TITLE
FileBeats  incorporation [FeatureRequest]

### ISSUE THREAD

**Issue by edmitchellVS** [ukncsc/lme#146]
**Is your feature request related to a problem? Please describe.**
We are looking to enable logging for Linux and Apple Mac devices however this is not possible with WinLogBeats

**Describe the solution you'd like**
I would like to utilise File or AuditBeats to enable logging for Linux servers and Apple Macs

**Describe alternatives you've considered**
Installing File/AuditBeats locally on the host server and opening up the ports  to the docker network using docker-compose and shipping logs to Elasticsearch or log stash directly.
Pulling the docker image for File/AuditBeats and configuring File/AuditBeats.yml to work in the LME docker network

**Additional context**
I think I can probably work out how to do both of the above however I am not sure about how this work affect the LME docker package, if it will be wiped at next upgrade including any config changes etc.

**Comment by duncan-ncc** [comment]
Closed due to project archive
