### ISSUE TITLE
Can't Install Sysmon on Win10

### ISSUE THREAD

**Issue by coleJ98** [ukncsc/lme#15]
Hi,

I was wondering if you could help me out with installing Sysmon on win10 machine using Scheduled Tasks GPOs.

I am currently testing this with my testing environment which consists of WinServer2012 (DC); win10; win8.1 and win7 workstations.

I followed your guide by creating a GPO for scheduled Task where NT AUTHORITY\System will execute a sysmon install script (update.bat) on a share. This batch file is located in the sysvol as suggested in the guide. The full path is: **\\\FDQN\sysvol\FDQN\scripts\Sysmon\update.bat**

The issue I am having is that sysmon is installed on all the machines except win10.

To test this, I downloaded Sysinternals suite and opened a command prompt as local system (NT AUTHORITY\System) using PSExec. I tried to manually trigger the Scheduled Task as a **local system user** using the following command: **schtasks.exe /RUN /TN "Install Sysmon"** (where "Install Sysmon" is the task name). Manually triggering the scheduled task successfully executes the update.bat file and sysmon is installed.

I cannot understand what the issue is and why the update.bat file won't execute automatically through scheduled task. If you have any knowledge on how to fix this then please let me know!

This is the current setting of my scheduled task:
![image](https://user-images.githubusercontent.com/9300684/57138607-03acc400-6dab-11e9-9127-bc656251dabf.png)

**Comment by duncan-ncc** [comment]
Hi @coleJ98 the task should be set to "Run whether user is logged on or not"

**Comment by coleJ98** [comment]
Hi @duncan-ncc I have tried that aswell how ever it does not resolve the issue! 

If I choose this option, it automatically chooses "Do not store password. The task will only have access to local resources". Doesn't this mean that the local system will not be able to access the share (sysvol) to copy the executable and the config file?

![image](https://user-images.githubusercontent.com/9300684/57139070-2e4b4c80-6dac-11e9-850c-f2585962bb3f.png)

**Comment by duncan-ncc** [comment]
@coleJ98 The settings you have shown in the screenshot above, With the "Do not store password" setting ticked are the same as we have used for trial clients etc. 

Are there any errors in the windows event logs suggesting why the task is not running? 

Also worth mentioning.. Did you change the Path in actions?

**Comment by coleJ98** [comment]
Hi @duncan-ncc  I have checked the logs under Task-Scheduler/Operational logs and I cant see any errors, the logs suggest that the task was registered, started and ended.

Under the actions tab, I do have my path set to where my update.bat file is located in sysvol:
![image](https://user-images.githubusercontent.com/9300684/57141601-7c634e80-6db2-11e9-999c-2c7048809d1e.png)

I just cannot figure out what the issue is here. Sysmon is installed on all workstations as well as the testing DC but just not win10

**Comment by nebblkshts** [comment]
I got mine to run but the batch file is not downloading and install the sysmon and sigcheck. I had to hard code the domain name instead of the variable because the variable was adding spaces. if you echo the variable you see "\\domainname \sysvol\domainname \folder\file" Once I hardcoded the domain name in there I got down to where the sysmon install complains about the XML having white space at line 530 and 531. I am stuck here.

**Comment by duncan-ncc** [comment]
@nebblkshts the whitespace was fixed in #14, We are still in alpha it is suggested that people make sure they are running the very latest version.
The sysmon file is external to this project so if you are having issues with the swiftonsecurity xml I suggest you post a bug there.

**Comment by nebblkshts** [comment]
@duncan-ncc Thank you. I will make sure I keep up to date. Sorry I did not mean to say it was LME was at fault for swiftonsecurity xml issues. I was just trying to help with the things I was seeing.

**Comment by duncan-ncc** [comment]
@nebblkshts No problem! We want this install to be as quick and painless for everyone. 

@coleJ98 Can I suggest deleting the GPO and batch file and making sure you have the latest version from here?
