### ISSUE TITLE
How can I get a friendly HTML export of a day's worth of events for 1 endpoint?

### ISSUE THREAD

**Issue by divadiow** [ukncsc/lme#150]
We've had an incident on an endpoint that has resulted in some very interesting events logged in LME. We'd like to report/export on all these events before the retention policy sweeps it all away. Is there a nice way to export all ~9000 events I see in the Events tab of a host, with each events linked details to HTML, so they can be browsed and expanded as if you were in LME looking at live data?

![image](https://user-images.githubusercontent.com/62958974/195304564-0bc3a3b1-8a11-425a-8079-21a9d043930d.png)

OR exclude this section of log from the retention policy. mark is as persistent?

**Comment by duncan-ncc** [comment]
Hello, 

I haven't personally tried it so your mileage may vary, however [elasticsearch-dump](https://github.com/elasticsearch-dump/elasticsearch-dump) appears to have the capability to save off data based on a query.

**Comment by duncan-ncc** [comment]
Closed due to project archive
