### ISSUE TITLE
Kibana Container crash every few seconds

### ISSUE THREAD

**Issue by LeitLei** [ukncsc/lme#151]
My Kibana container crash every few seconds since today.
In the logs I can see the following error:

> FATAL  Error: Unable to complete saved object migrations for the [.kibana_task_manager] index. Please check the health of your Elasticsearch cluster and try again. Unexpected Elasticsearch ResponseError: statusCode: 429, method: PUT, url: /.kibana_task_manager_7.17.5_001/_mapping?timeout=60s error: [cluster_block_exception]: index [.kibana_task_manager_7.17.5_001] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];,

Any idea, how can I fix this?

Docker version: 20.10.20
Ubuntu 20.04.5 LTS
LME Version 0.4

_./deploy.sh upgrade_ doesn't work because I've get this error for the dashboard_update user password:
>  The password you have entered was invalid or the elastic service did not respond, please try again.

But the password is definitely correct.

Best Regards
Patrick

**Comment by LeitLei** [comment]
I found here (https://github.com/ukncsc/lme/issues/126 ) users with the same issue.

Logging in to https://your-lme-kibana-instance/app/management/data/index_lifecycle_management/policies/edit/lme_ilm_policy isn't possible, because dashboard isn't availible:

> Error: Connection failed
> An error occurred when connecting to XX.XX.XX

**Comment by duncan-ncc** [comment]
Hello,
It looks like your storage has filled up, I would suggest that you increase your disk space or remove some of the older data from your cluster to allow kibana to start again. 
We have a new version of LME releasing shortly which includes a more robust ILM policy.

**Comment by LeitLei** [comment]
Hello @duncan-ncc,

thanks for your help.
Is there a "best practice" how remove older data from my cluster?

Sorry for this question. But I'm not a heavy user with Docker.

Best Regards
Patrick

**Comment by duncan-ncc** [comment]
Hi, 

No we don't haver any guidance on the removal of data, Elastic do have documentation on how to delete index's via the API etc
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-delete-index.html

Thanks,
Duncan

**Comment by LeitLei** [comment]
Hi @duncan-ncc,

I see that a new version was released.
Is there now any setting that we have to change to prevent running full of space?

Best Regards
Patrick

**Comment by duncan-ncc** [comment]
Hello, 
We released an update to the script as part of the standard release procedure we use, The full update should be coming out this morning, to apply it you will need to follow the upgrade instructions and run the deploy script with the upgrade option.

In relation to to disk space we have "Modified the retention settings to include a more conservative disk size requirement, assuming 2GB of logs per day rather than 1GB"
