### ISSUE TITLE
Update to 0.5: Unable to determine retention policy

### ISSUE THREAD

**Issue by LeitLei** [ukncsc/lme#154]
Hi,

I followed your update guide to update from 0.4 to 0.5.
After _sudo ./deploy.sh upgrade_ and entering the passwords, I've get the error:

> [X] Setting the kibana system password, note the username will now be 'kibana_system' rather than 'kibana' {}
> [X] Setting logstash writer role {"role":{"created":false}}
> [X] Setting dashboard update role {"role":{"created":false}}
> [X] Setting Elastic pipelines {"acknowledged":true}
> [X] We think your main disk is 68G on /dev/mapper/ubuntu--v g-ubuntu--lv
> **[!] Unable to determine retention policy - exiting**

Can I ignore this?

Best Regards
Patrick

**Comment by duncan-ncc** [comment]
Hi @LeitLei, Is your disk actually 68 GB? 
With elastic default Watermarking set to 80% that would only give you 54.5GB of useable log storage. 

The error above should be more verbose and point out that we are expecting a disk which has 100G+ of usable space for elastic, (so ~113 GB disk to account for OS install etc).

In relation to your specific case, your upgrade will not have completed sucessfully.

**Comment by LeitLei** [comment]
Thanks. After set the disk to 120GB, all works fine.

Best Regards
Patrick
