### ISSUE TITLE
Manually running a cleanup from ssh if GUI not accessible - space keeps running out

### ISSUE THREAD

**Issue by divadiow** [ukncsc/lme#156]
Not sure if this is because we messed with the shards when on 0.4 but we were hoping the space requirements would reduce somewhat with .5. We keep running out of space even with a reasonable retention policy. 

Should we -not- wish to keep increasing the disk but instead flush out some of the oldest logs, could this be done from the command line somehow?

**Comment by duncan-ncc** [comment]
Closed due to project archive
