### ISSUE TITLE
winlogbeat service does not start

### ISSUE THREAD

**Issue by kort3x** [ukncsc/lme#159]
**Describe the issue**
The service does not start

**To Reproduce**
Start-Service winlogbeat

**Expected behavior**
service starts

**Error**
> Start-Service : Der Dienst "winlogbeat (winlogbeat)" kann aufgrund des folgenden Fehlers nicht gestartet werden: Der Dienst winlogbeat kann nicht auf dem Computer . gestartet werden.
> In Zeile:1 Zeichen:1
> + Start-Service winlogbeat
> + ~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
>     + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand

**Windows Event Collector (please complete the following information):**
 - OS: Server 2019 1809
 - Winlogbeat.exe version: winlogbeat version 8.5

**Linux Server (please complete the following information):**
 - Docker: 20.10.21
 - Linux:  Ubuntu 22.04.1 LTS

**Additional context**
- German Windows Server 2019
- running winlogbeat.exe in foreground exits with a file not found error and:

> Exiting: failed to create new event log: failed in processor.javascript: failed to open file C:\Program Files\lme\winlogbeat-8.5.0-windows-x86_64/module/security/config/winlogbeat-security.js

**Comment by duncan-ncc** [comment]
Hello, 

When running in foreground did you do this with an admin prompt? The failed to open is likely to be caused by lack of existance or permissions. 

Thanks,
Duncan

**Comment by cbmclaughlin256** [comment]
I was running into the same issue. The service did not start. Running the command manually as an administrator gave the same message that it wass unable to open "C:\Program Files\lme\winlogbeat-8.5.0-windows-x86_64/module/security/config/winlogbeat-security.js."

![winlogbeat-module](https://user-images.githubusercontent.com/109623748/206722577-68700a32-5b63-43ba-a623-1080bfa02541.PNG)
![winlogbeat-cmd](https://user-images.githubusercontent.com/109623748/206722619-37ec6463-efc5-43f3-9f44-3e85655f4317.PNG)

This is running on English Windows Server 2019 using the winlogbeat zip file linked in the directions. I also tried the 8.5.3 version [here](https://www.elastic.co/downloads/beats/winlogbeat). Neither zip file had the "config" folder in either the security or sysmon folders.

I replaced the contents of the winlogbeat.event_logs: section with some lines from the example YAML file and the service started. It looks like I'm at least getting login info in the dashboard.

[This discussion](https://discuss.elastic.co/t/cant-get-windows-winlogbeat-8-0-to-run-the-system-cannot-find-the-path/298670) says: "There are no more .js files for the script processors. So remove script processors and checkout the new module docs and also the default config that comes with 8.0."

What I have in the winlogbeat.yml file now:
winlogbeat.event_logs:

  - name: Microsoft-Windows-Sysmon/Operational

  - name: ForwardedEvents
    tags: [forwarded]
  
output.logstash:
What was originally there

**Comment by kort3x** [comment]
I also saw that discussion on .js files being obsolete - will try cbmclaughlin256 method.

**Comment by divadiow** [comment]
yes. I've cleared the script processors part out and the service starts now

![image](https://user-images.githubusercontent.com/62958974/211574358-a62e49a9-1113-4764-a6d9-950a7f050d53.png)

**Comment by duncan-ncc** [comment]
Closed due to project archive
