### ISSUE TITLE
[BUG] "LME Status dashboard" empty, but Kibana is full of logs from clients

### ISSUE THREAD

**Issue by 7MinSec** [ukncsc/lme#16]
**Describe the issue**
I think this could very well be a "just me" issue, but my LME Status Dashboard is empty, yet under "Discover" the events are pouring in.

**To Reproduce**
1. Follow LME instructions until you get to the point of installing winlogbeats service.

2. Notice that Kibana is up and running but not collecting any events.

3.  Don't follow the directions and install the winlogbeat service without the files being in the right place :-(

3.  Stop/uninstall winlogbeat

4.  Put files in the right paths :-)

5. Reinstall winlog beat

6.  Check that winlogbeat is started and winlogbeat log is free of errors.

7. Check Kibana and see under "discover" that events are pouring in.

8.  Click Dashboard->LME Status Dashboard and note 0 events and 0 computers found.

9.  Delete the dashboard and reimport for good luck.

10.  Still an empty LME status dashboard.

Anything else I can try?

Thanks,
Brian

**Comment by duncan-ncc** [comment]
Hi @braimee did you delete the default index as well or refresh the field mappings?
The only thing I can think of at the moment is your fields haven't been updated (if this is the case you will see an orange triangle when you expand an entry in discover)

**Comment by 7MinSec** [comment]
Hey there (and holy cow thanks for all your quick replies!), all I did on the Kibana side is run the install, log into the interface and then import the LME dashboards.  However, maybe I am experiencing the issue with fields?  Here's one of my events expanded:

<img width="1018" alt="Screen Shot 2019-05-03 at 11 30 25 AM" src="https://user-images.githubusercontent.com/17596787/57151592-ecfc7200-6d96-11e9-9943-ae1f15ccf881.png">


Brian

**Comment by duncan-ncc** [comment]
Hi @braimee it does look like you are having an issue with the fields (without looking into it in more detail its hard to say why this happened)
If you go to Management > Index Patterns and press Refresh Field List (in the top right) this should fix your issue.

**Comment by 7MinSec** [comment]
I followed these steps but I might've broken the world even more now?  After refreshing fields, my individual events look better:

<img width="667" alt="event" src="https://user-images.githubusercontent.com/17596787/57312394-11b45a80-70b3-11e9-99df-237caecb7a2b.png">

But the dashboard now looks all sad:

<img width="1238" alt="dashboard" src="https://user-images.githubusercontent.com/17596787/57312409-1aa52c00-70b3-11e9-9956-2a80efeea84f.png">

Should I be reimporting that dashboard .json file in these steps at all?

Brian

**Comment by duncan-ncc** [comment]
Hi @braimee 

Can you confirm you have the lastest Dashboards? It does look like you have old dashboards (the fields should be mapped properly if you imported the dashboards for example), can you make sure you have the latest from the git (dashboard 0.1.2.json)

**Comment by 7MinSec** [comment]
That did it, thank you!  And thanks for all your great work on this, I'm REALLY excited to watch this project as it moves forward.  Also, I talked about LME on my podcast this past week so I'm trying to spread the word :-)
