### ISSUE TITLE
[BUG] Disc space detection in deploy script has range of values it won't handle

### ISSUE THREAD

**Issue by damerell** [ukncsc/lme#161]
`deploy.sh` does:
```
  if [ "$DISK_80" -lt 30 ]; then
    echo -e "\e[31m[!]\e[0m LME Requires 90GB of space usable for log retention - exiting"
    exit 1

  elif [ "$DISK_80" -ge 90 -a "$DISK_80" -le 179 ]; then
    RETENTION="30"
```

If DISK_80 is between 30 and 90 then RETENTION is never set, and since it is then used eg in `"min_age": "'$RETENTION'd"`, this won't work. Suspect '30' is just a typo for '90' in the first line quoted here.

I'm not really sure the whole "so much disc space -> so many days" mechanism here makes sense - surely it is highly dependent on client numbers - but other issues address that.

The repository I cloned goes up to commit 2ec0b81546bd2f460eb2e09584121b39f6e89a67 (Date:   Mon Nov 21 09:06:36 2022 +0000)

**Comment by duncan-ncc** [comment]
Closed due to project archive
