### ISSUE TITLE
[BUG] - Error on 'Interesting process creation' dashboard

### ISSUE THREAD

**Issue by lousybastard** [ukncsc/lme#17]
go to dashboard > interesting process creation - advanced an error displays.

![image](https://user-images.githubusercontent.com/50493287/57602337-854ce080-7567-11e9-9f25-9985e71407ae.png)

**Comment by duncan-ncc** [comment]
Can you please confirm what version of the dashboard and winlogbeat you are using.

**Comment by lousybastard** [comment]
i am using 1.1 dashboard and winlogbeat 6.7. I also tried with 1.2 dashboard and winlogbeat 7.0 (put to last 7 days) and still the same error is given

**Comment by duncan-ncc** [comment]
Hi,
That error does not look like it comes from 0.1.1b as it mentions "winlog." , 0.1.1b dashboards are not compatible with Winlogbeat 7 
The error here is most probably that you do not have the correct field mappings between Winlogbeat and the Dashboard.
Please use Winlogbeat 7+ with 0.1.2 dashboards and set the time frame to a period for which you have data that has been ingested by Winlogbeat 7.

I also suggest that after importing the 0.1.2 dashboards and having Winlogbeat 7 running you refresh your field list using "Management > index patters > Winlogbeat-* >  Refresh field list"

**Comment by lousybastard** [comment]
for 0.1.2 dashboard i am getting this, could not locate error which made me fallback to the 0.1.1b

![image](https://user-images.githubusercontent.com/50493287/57607748-702a7e80-7574-11e9-8242-fd4800e2360e.png)

**Comment by lousybastard** [comment]
also for 0.1.2 same field i am getting this, though the error doesnt pop up (dashboard > interest process creation: (5 of 25 shards failed) i am getting that. is that ok?

![image](https://user-images.githubusercontent.com/50493287/57608122-16768400-7575-11e9-8790-c0c1ca46b34c.png)

**Comment by duncan-ncc** [comment]
Can you please try downloading the 0.1.2 dashboards again, Delete all of the dashboards and index templates etc and then import 0.1.2 the could not locate error is not 0.1.2 (it hasn't got the ECS winlog. prefix)

The 5 of 25 shards failed issue could be caused for many reasons, The most common we see is due to searching over a large time range on a dashboard or using a very wide search with a long time range on discover tab.

**Comment by lousybastard** [comment]
still same issue after deleting and downloading again, i went to index pattern, and that event_data.ConfigurationFileHash.keyword is not there hence getting same error

![image](https://user-images.githubusercontent.com/50493287/57612461-91dc3380-757d-11e9-843e-3db706d550a6.png)

**Comment by duncan-ncc** [comment]
Hi,
If it is not in the index pattern then I suggest you wait till a sysmon install is launched and then refresh.
You can see the field is included with the LME index template [here](https://github.com/ukncsc/lme/blob/master/Chapter%204%20Files/dashboard%200.1.2.json#L948) on line 948.

**Comment by lousybastard** [comment]
fields after import is 972 and event_data.ConfigurationFileHash.keyword is there

![image](https://user-images.githubusercontent.com/50493287/57617923-a1ae4480-758a-11e9-9f1c-1d096a4c54b6.png)

fields after refresh Management > index patters > Winlogbeat-* > Refresh field list is 455 and 

![image](https://user-images.githubusercontent.com/50493287/57617996-dde1a500-758a-11e9-964f-9b2bb39f1194.png)

so i was checking after the refresh.

**Comment by duncan-ncc** [comment]
The index template has both v6 and v7 mappings in so when you refresh after import it removes the ones that do not map to data. It looks like you have no Sysmon configuration data in your Elasticsearch if the field is not present after a refresh.
