### ISSUE TITLE
Sysmon error sending data

### ISSUE THREAD

**Issue by shokcwave** [ukncsc/lme#20]
Hi i have been running throught the installation instructions to try and get LME up and running i have got to the ned of chapter 2 installing sysmon via GPO.

On my test machine i can see sysmon has been installed as a service and is currently running, however when i check the event log to see if it is forwarding logs i cannot see the Applications and Services Logs/Microsoft/Windows/Sysmon entry.

If i have a look at the eventlog-forwardingplugin log i see this error message 'The subscription lme is created, but one or more channels in the query could not be read at this time.'

is this the reason why event logs do not appear to be getting forwarded?

Many thanks
Mark

**Comment by duncan-ncc** [comment]
Hi Mark,

If you do not have the ```Applications and Services Logs/Microsoft/Windows/Sysmon/Operational``` path in eventviewer (launched as admin) then your sysmon is not installed properly.
If sysmon is running but there are no logs being generated then it sounds like sysmon is running with a configuration that is not generating alerts. 
Did you use the SwiftOnSecurity XML file or a different one? 

Sysmon and Event Forwarding are two separate things, are you seeing no events in 'forwarded events' on the windows server which is configured as the collector?

**Comment by shokcwave** [comment]
Hi sorry my mistake, i didn't open the event viewer as admin, now i have done that sysmon is there and the logs are appearing in the forwarded events on the collector.

thank you for the prompt reply.

**Comment by duncan-ncc** [comment]
Glad to hear it is working for you
