### ISSUE TITLE
No logs being sent to Linux server

### ISSUE THREAD

**Issue by shokcwave** [ukncsc/lme#21]
Hi i appear to have another slight issue i have managed to run through Chapter 3A now, i have installed the ubuntu server and ran the easy script everything seemed to work ok with no errors as far as i could see, i can log into Kibana and i have imported the dashboards, however i don't seem to be receiving any log files in Kibana, where can i check to see if my logging collector server is pointing to the correct db server?

**Comment by duncan-ncc** [comment]
Hi,

Does winlogbeat show as running and automatic on the windows box? 
The config which tells winlogbeat where to send the logs is in the zip file you copied from the linux box to the windows box.

**Comment by shokcwave** [comment]
Hi Duncan it is showing as a service and it is running, however this is where i think i may have gone wrong with the config, when i have a look in the winlogbeat.yml file the hosts: line has our domain.local:5044 entry should this point to the db server?

**Comment by duncan-ncc** [comment]
Hi, The winlogbeat.yml should show the linux server FQDN not just the domain, This likely means that the linux server name was not correctly entered in the install script which might lead to certificate errors further down the line.

**Comment by shokcwave** [comment]
Can i rerun the install script again or am i better reloading ubuntu and starting from a fresh?

**Comment by duncan-ncc** [comment]
You should be fine to run ```./deploy.sh uninstall``` and then rerun ```./deploy.sh install```.

**Comment by shokcwave** [comment]
I have uninstalled and reinstalled and this time i have filled out the correct details, copied over the new certs to the logging server and it is now working, thank you very much for your help.

**Comment by duncan-ncc** [comment]
Glad to hear it wasn't to complicated a fix!
