### ISSUE TITLE
[BUG] Server 2019 collector returning 404 on /wsman/SubscriptionManager/WEC access

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#23]
I ran into this issue when configuring a Server 2019 as the collector:

https://support.microsoft.com/en-ca/help/4494462/events-not-forwarded-if-the-collector-runs-windows-server-2019-or-2016

I had to run the commands contained therein, and then restart the winrm and event collecting services. Sounds like default Server 2019 install will have this problem.

Probably want to add this to the guide, or similar.

**Comment by duncan-ncc** [comment]
Hi @tfriesen 
Thanks for highlighting that this isn't as clear as it could be, We actually highlight this issue in the [troubleshooting guide](https://github.com/ukncsc/lme/blob/master/docs/troubleshooting.md).
