### ISSUE TITLE
[BUG] WEC XML Configuration mode not Custom

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#24]
On server 2019, using the default XML provided,  'wecutil cs lme_wec_config.xml' returns

Warning: Configuration mode for the subscription is not Custom. Delivery properties are not
customizable for such mode. As a result, Delivery node from the provided configuration file
will be ignored.

Changing \<ConfigurationMode\> on line 16 from 'Normal' to 'Custom' resolves the issue, and allows the XML to specify custom intervals.

**Comment by jordanmills** [comment]
This has been an issue with wecutil since... probably since it's been around.  The xml files it exports, and most examples, have duplicate settings (mode not custom, but custom settings included), and wecutil barfs when it encounters that case.
