### ISSUE TITLE
Using OpenDistro instead of standard ELK

### ISSUE THREAD

**Issue by doftorul** [ukncsc/lme#25]
Since the OpenDistro for Elasticsearch fork comes with some much needed security plug-ins and the changes are minimal to the Kibana dashboards, would you consider using it instead of the original elasticsearch release ?

The "essential" plugins being Alerting and of course out of the box security via Authentication, RBAC and encryption at rest and on the fly.
There is also the SQL plugin which allows users not familiar with the elastic ecosystem to manipulate their stored data without a steep learning curve encouraging perhaps a better adoption.

https://opendistro.github.io/for-elasticsearch/features/security.html

**Comment by duncan-ncc** [comment]
Hi @doftorul 
We have a number of improvements on the roadmap for LME, RBAC and Alerting are on the list. 
We are currently trying to get a functional solution before investigating the different ES RBAC and alerting offerings which could be integrated.
