### ISSUE TITLE
[BUG] Sysmon update.bat does not change to C: drive

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#28]
I've run into this issue on a couple of my hosts. For reasons that remain unclear, they are running sysmon's update.bat from a drive other C:, like H: or K:. (Though this is unusual, I am surely not the only person who will have this issue). The problem is that when update.bat runs "chdir %SYSMONDIR%", it assumes that we're already on the C: drive, and proceeds to execute commands as though they were local. But because we're still on H: or whatever, the current directory is not actually changed.

I see three ways of fixing this:

1. Add a 'C:' command to the batch file either before or after each chdir %SYSMONDIR% (what I am currently doing)
2. modify the scheduled task to start in a location on C: (which is to say, make a note in documentaiton)
3. change the script so all commands are executed from absolute paths, ie SET SYSMONBIN=%SYSMONDIR%\Sysmon64.exe or similar

1 seems a little hacky, but is simple and it works. 2 would be an easy fix, but something about it does not fill me with confidence. 3 seems like the most robust fix, but could introduce other bugs without testing the script.

**Comment by duncan-ncc** [comment]
Hi @tfriesen - I think for this one we will add it into the GPO so that it is more easily changed. 
In your environment is C drive not your main drive from where windows is installed?

**Comment by tfriesen** [comment]
Yup - on all the systems that seem to have this issue, Windows is, in fact, installed on C:. I haven't been able to discern the pattern yet on why some systems have this issue and others don't.

**Comment by duncan-ncc** [comment]
We have been unable to replicate this, a GPO change on the scheduled task to force the start location will be added.
