### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by coleJ98** [ukncsc/lme#29]
Hi,

This is a great guide! I would like to suggest using ELK stack version 7.1.1 with OpenDistro docker image instead. This is because the xpack security plugin is now free to community users! This is a really easy switch over with great benefits (you just have to rebuild the docker images and configure basic security). Benifits such as Transport layer TLS, HTTP layer TLS and role based authentication!

Also, Sysmon10 is released! I have not played much around with the new schema but EventId 22 can now log DNS on each endpoint! Something for the future improvements

**Comment by duncan-ncc** [comment]
Hello,

We have been looking at OpenDistro and Elasticsearch basic to see which fits best with LME and should have a decision shortly.

Sysmon10 is already supported by LME and the documentation was changed to reflect this in commit 1201a9d5d15578684ba80494159eee1d34c74dae
