### ISSUE TITLE
[FeatureRequest] Add Support for Mac OSX

### ISSUE THREAD

**Issue by brampat** [ukncsc/lme#30]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Would like to see integration for Mac OSX

**Describe alternatives you've considered**
No other alternatives tried

**Additional context**
Since more organisations start using Mac OSX, it could be convenient to add support / integration for Mac OSX event monitoring
Both OSSEC and OSSIM support OSX apparently: https://www.reddit.com/r/sysadmin/comments/5nt24n/cheap_siem_solution_for_apple_mac_os_x/
And MIDAS was designed specifically around Mac OSX:
https://www.alienvault.com/blogs/labs-research/securing-mac-os-x-with-usm-and-midas

**Comment by duncan-ncc** [comment]
Closed due to project archive
