### ISSUE TITLE
[FeatureRequest] Add support for Mobile devices (Android / iOS)

### ISSUE THREAD

**Issue by brampat** [ukncsc/lme#31]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Would like to see integration for mobile devices (tabets and smartphones) running Android or iOS.

**Describe alternatives you've considered**
No other alternatives tried

**Additional context**
With BYOD policies and guest / internal Wifi, more people are using smartphones and tablets on office networks. Therefore adding support for Android and iOS integration could be useful.

**Comment by duncan-ncc** [comment]
Closed due to project archive
