### ISSUE TITLE
[BUG] Changes to Sysmon.xml not updating Sysmon's behaviour

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#32]
This one is a bit tricky to describe, so please bear with me, and may be a bug with Sysmon rather than LME.

**To Reproduce**
1. Update` \\<domain>\sysvol\<domain>\Sysmon\sysmon.xml` (or similar). In my case, I added a new entry to exclude some DNS names from eventid 22 to reduce some of the noise being generated. Specifically "end with" my domain root and "begin with" 'exch1', to omit my exchange cluster.
2. Wait

**Expected behavior**
After the update.bat script runs, I would expect that Sysmon's behaviour change to reflect the new configuration.

It does not. Sysmon continues to log and forward eventids 22 where the QueryName includes my domain root and various 'exch1' DNS names.

If I run Sysmon64.exe -c , I can see the new configuration reflected in the output, but the old behaviour persists. If I force an uninstall and reinstall of Sysmon, the behvaiour is updated and correct.

All boxes I've tested on so far are Windows Server 2012 R2.

**Comment by duncan-ncc** [comment]
Hi @tfriesen, Thats an interesting one I have not experienced yet.
If you restart the service rather than reinstalling the Sysmon driver does the running configuration match the configuration you passed with the '-c' command?

**Comment by tfriesen** [comment]
If I manually start and stop the service, yes it seems to take the new configuration.

**Comment by tfriesen** [comment]
Based on @duncan-ncc 's suggestion, I added

`sc stop Sysmon64`
`sc start Sysmon64`

to the bottom of the :updateconfig section of the update.bat script, which resolved my problem.
