### ISSUE TITLE
[QUESTION] Archive logs using Elasticsearch snapshots

### ISSUE THREAD

**Issue by kamouchka** [ukncsc/lme#34]
We are currently using LME for about Windows servers in our infrastructure. 
Due to disk space restrictions we can currently only keep two weeks of logs on the LME server.
We would like to achieve a log retention time of 90 days. 
Therefore we would like to backup and archive our LME logs to another location (e.g. AWS S3).
We are thinking of using the Elasticsearch snapshot feature for it. 
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

Has anyone looked into that before?
Any hints on where to configure this within LME?
Thank you.

**Comment by a-d-a-m-b** [comment]
Hi @kamouchka - glad to hear that you're using LME and it's being helpful to you.

Snapshot/Restore procedures differ based on the version of ELK that you're using. The build that is part of the main branch is a little more 'hands-on' (Elastic 7.3 includes a UI feature). We don't provide the means to enable this out of the box, but you can add in an environmental variable ('path.repo') and may need to add another volume mount point within the Elastic definition in the docker-compose file.

This may change in the future, but it is not part of the core LME product and therefore support, at this time. 

Hope this helps

**Comment by a-d-a-m-b** [comment]
To snapshot directly to S3 you will also need to add in a plug-in to do so. Again, this is outside of the core LME project's scope so we won't be able to provide comment on how to achieve this, but Elastic's documentation will help:

https://www.elastic.co/guide/en/elasticsearch/plugins/7.3/repository-s3.html
