### ISSUE TITLE
[BUG] wrong port number in diagram

### ISSUE THREAD

**Issue by m0gjr** [ukncsc/lme#35]
Diagram in Chapter 1 shows TCP port 5986, should show port 5985 to be consistent with the rest of the documentation and the system behaviour.

https://github.com/ukncsc/lme/blob/master/docs/eventforwarding_overview.jpg

**Comment by duncan-ncc** [comment]
Hi @m0gjr - I will change this, I agree that it should be consistent, Those which choose to use HTTPS connections would require 5986 so this will also be clarified in the documentation
