### ISSUE TITLE
[BUG] deploy.sh uninstall not resetting ElasticSearch creds

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#39]
**Describe the issue**
Deploy.sh is not removing all of the artifacts from the install. Specifically, the elasticsearch password is being retained.

**To Reproduce**
1. deploy.sh install
2. deploy.sh uninstall
3. deploy.sh install

**Expected behavior**
I can re-install LME. Instead, the script hangs at "[x] Waiting for elasticsearch to be ready".

If I run the test command from the deploy.sh script:

curl --cacert certs/root-ca.crt --user elastic:temp -s -o /dev/null -w ''%{http_code}'' https://127.0.0.1:9200

It returns 401, (unauthorized). If I change the password from 'temp' to the password that was generated from my previous install, the test succeeds with code 200.

Using a fresh install of Ubuntu server 18.03.04 LTS, and the latest code from git. The first LME install partly failed due to storage issues with deploying the docker images and didn't generate the files_for_windows.zip file, which is why I am trying to reinstall.

**Comment by tfriesen** [comment]
This seems to be because the elasticsearch creds are stored in the elasticsearch database, which is stored in the es docker volume (which all makes sense). However, the es docker volume is not removed on deploy.sh uninstall. This may be intentional, so that es/log data would be retained between upgrades/reinstalls.

In other words, docker purge --volumes seemed to resolve my issue

**Comment by tfriesen** [comment]
Possibly related issue: after purging the docker volumes and fresh installing LME, I attempt to log in to Kibana with the generated password (and the user 'Kibana', which the script neglects to mention), and my browser returns:

{"statusCode":403,"error":"Forbidden","message":"Forbidden"}

The username/password pair is correct, because if other information is entered, I get a failed login at the Kibana login screen.

**Comment by duncan-ncc** [comment]
Hi @tfriesen,
We made the choice to not remove the Elasticsearch database upon uninstall to prevent accidental deletion of data, It would probably make sense for us to highlight this though.

The Kibana password is not meant to be used by end users to authenticate to Kibana, It is for authenticating Kibana backend to Elasticsearch. Users should be using the 'elastic' user. I will update the script to reflect this better in the future.

**Comment by tfriesen** [comment]
Hi @duncan-ncc 

Thanks for the quick reply. What you say makes sense, and I see the changes to the deploy script. Recommend also adding a note that the user may need to wait a minute or two after running deploy.sh uninstall before running "docker volume rm lme_esdata", otherwise they will get the error:  "Error response from daemon: remove lme_esdata: volume is in use..."

A note that the elasticsearch user password has not been changed and will prevent reinstallation unless the data is removed might also be worthwhile.

**Comment by duncan-ncc** [comment]
A warning about the underlying database not being removed by the uninstall command and instructions for manual deletion was added in 3a5e93993ef090b743d7e0e68dd7c6c5e8f6eec7.
