### ISSUE TITLE
Retention period

### ISSUE THREAD

**Issue by shokcwave** [ukncsc/lme#53]
Hi my installation of LME seems to be removing events older that 6 day, i have tried to look for the retention period in the docker-compose-stack.yml file however i cant find the entries mentioned in the chapter 3 documentation, any ideas.

thanks
Mark

**Comment by duncan-ncc** [comment]
Hi Mark,
You can manually update this by going to the kibana interface and then:
Management > Index Lifecycle Policies > lme_ilm_policy

If you scroll to the bottom you will see similar to the below
![image](https://user-images.githubusercontent.com/43746821/72253527-a6d00180-35f9-11ea-84d1-68cc426aad6e.png)

You can change the number of days retention there.

Note that this will only apply to new indices unless you also go into Management > Index Management, select the index that you wish to retain following this new policy (you can select multiple) and in the "manage index" drop down select "add life cycle policy" and then select lme_ilm_policy.


Thanks

**Comment by shokcwave** [comment]
This worked fine, thank you very much
