### ISSUE TITLE
[FeatureRequest]

### ISSUE THREAD

**Issue by kevingraygithub** [ukncsc/lme#55]
Hey Guys, would be worthwhile looking at Olaf Hartongs sysmon configs (if you weren't already aware)

https://github.com/olafhartong/sysmon-modular/blob/master/README.md

**Comment by duncan-ncc** [comment]
Hi Kevin,

We chose to suggest the user uses the swiftonsecurity config as it is well known, regularly updated and easy for the user to get started with, it will not fit every environment and the sysmon config will likely need tailored on a per environment basis for fully effect however this is outside the scope of LME at the moment and is an exercise left for the reader.

Thanks,
Duncan

**Comment by kevingraygithub** [comment]
👍
