### ISSUE TITLE
[FeatureRequest] Include ElastAlert (or similar) as part of default install

### ISSUE THREAD

**Issue by tfriesen** [ukncsc/lme#58]
**Is your feature request related to a problem? Please describe.**
Out-of-the-box, ElasticSearch does not support alerting on events for the free versions.

**Describe the solution you'd like**
Several third-party tools exist which allow for the inclusion of alerting, such as ElastAlert by Yelp: https://github.com/Yelp/elastalert

**Describe alternatives you've considered**
Switching to OpenDistro for ElasticSearch is an alternative, but there may be compatibility issues, and alerting methods are limited to web hooks.

**Comment by a-d-a-m-b** [comment]
Hi @tfriesen - 100% agree that this is a required feature and is already in the pipeline. It will (hopefully)  be included in the next release, if not the next. We are also looking to include some standard dashboards/visualisations supporting the Elastalert outputs too. 

What types of things would be useful to see in an Elastalert dashboard or visualisation?

**Comment by tfriesen** [comment]
An excellent question. I'm not too sure. I've played around a bit with the built-in Winlogbeat and Auditbeat dashboards. They have a few interesting metrics, but nothing that really thrills me.

One thing that I find myself interested in knowing is how many hosts are report in with vs without Sysmon. Also number hosts seen in the past X time vs X-1 interval, and so on. Basically a way of keeping track of what proportion of hosts on my network are correctly configured and reporting in, how that's changing, etc.

**Comment by tfriesen** [comment]
Closed due to inclusion of 'Detections' in v0.4
