### ISSUE TITLE
Enable queuing in logstash and document index limits.

### ISSUE THREAD

**Issue by anderoo6** [ukncsc/lme#59]
I've recently deployed a LME cluster onto a supported ubuntu OS and have experienced the following situation:

Winlogbeat will push all events including any historic events into the logstash container.
Logstash then pushes all of these events into elasticsearch, however if the push from elasticsearch fails then these events do not appear to be queued within logstash.

On my install, elasticsearch has set a 1000 shard limit. With each index using 4 shards and each day using a single index there is a maximum of 249 days worth of logging available before elasticsearch drops new events and the push from logstash to elasticsearch fails. In my specific case the cluster lasted a little under a week before running out of indexes due to the initial push of historic events.

The specific error in the logstash container logs is:
`[WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"winlogbeat-12.03.2020", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x2de12e62>], :response=>{"index"=>{"_index"=>"winlogbeat-12.03.2020", "_type"=>"_doc", "_id"=>nil, "status"=>400, "error"=>{"type"=>"validation_exception", "reason"=>"Validation Failed: 1: this action would add [4] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"}}}}`

As logstash does not appear to be queuing these events there does not appear to be any easy way to resend the dropped events now that I have deleted old indexes. Perhaps this is something specific to my install or I have missed something in the documentation however I was not aware that there was a limit to the number of days of event logs that the cluster would be able to handle.

**Comment by a-d-a-m-b** [comment]
@anderoo6 - is this issue resolved?

There is some instructions to up the shard count in Issue [https://github.com/ukncsc/lme/issues/60](https://github.com/ukncsc/lme/issues/60)

As stated in that issue, we are working on refining the deployments for larger organisations or for deployments with high data volumes.

**Comment by anderoo6** [comment]
My issue is resolved now I understand the behaviour, the method to re-index the old logs from Issue #60 is useful to know too.

**Comment by duncan-ncc** [comment]
Closed due to project archive
