### ISSUE TITLE
[FeatureRequest] Syslog support - Ideally switches and vmware

### ISSUE THREAD

**Issue by ptaylor2020** [ukncsc/lme#63]
**Is your feature request related to a problem? Please describe.**
No, although we have a use case for logging what our vmware hosts and switches are doing.

**Describe the solution you'd like**
Support for being able to log syslog messages directly.

**Describe alternatives you've considered**
no alternatives looked at,

**Additional context**

**Comment by duncan-ncc** [comment]
Syslog support was added in #68 
You will need to add a logstash filter or pipeline to get them into a more searchable format though.
