### ISSUE TITLE
[BUG] Security Dashboard panel_4 name is wrong

### ISSUE THREAD

**Issue by kennethgillen** [ukncsc/lme#64]
**Describe the issue**
After a fresh install of `master` from ~4 months ago and `dashboards v0.2.0.ndjson` import:

panel_4 on the `Security Dashboard - User Investigator` has heading `Sysmon event ID 1 - Process creation`.

In `dashboards v0.2.0.ndjson` the search ID that's hooked up to this panel:
`{"id":"e30872f0-e698-11e9-8be5-cd86dcca33f3","name":"panel_4","type":"search"},`
  - searching this ID you can see the ID "srch_sd_security_logs".

**To Reproduce**
n/a

**Expected behavior**
I'd exect this panel to be called "Security Log Events" or something simlar.

**Screenshots**
![lme_name_security_dashboard_user_investigator](https://user-images.githubusercontent.com/2727871/82094837-bd947b00-96f5-11ea-97c2-914115f7a02a.png)

**Comment by duncan-ncc** [comment]
Hi,
We will shortly be releasing new dashboards, This issue is fixed within those. 

Thanks.
