### ISSUE TITLE
Question regarding Scheduled Tasks

### ISSUE THREAD

**Issue by coleJ98** [ukncsc/lme#7]
Hi, Thanks for putting this together!

I was going through this guide and I was wondering if an adversary could possibly leverage the scheduled task and use it as privilege escalation.

Do you think running a scheduled task as NT AUTHORITY\System on the workstations which accesses the network shares introduces an additional attack surface?

Please let me know your thoughts on this. I don’t know if this is possible, but would it be best practice to run the task as local system user?

**Comment by duncan-ncc** [comment]
Hello, I think this forms a larger question around best practice on use of privileged accounts so I am going to answer purely in relation to LME and its scheduled task.

Installing the Sysmon driver requires elevated privileges, to use an account other than System we would need to create either a local admin or a domain privileged user and manage the life cycle around this account (and there are some known issues with non system accounts creating Scheduled Tasks via GPO on win10+)

The scheduled task and resulting files are created with strong ACLs in privileged folders, so only an administrative account should be able to edit these, At which point compromise has already occurred.

Ideally we would use another method of deployment which is designed for software deployment however GPO with scheduled tasks appeared to be the only solution that we can assume will be in place on the majority of environments.

If you do find a way to leverage the scheduled task for Priv Esc do let us know!

**Comment by coleJ98** [comment]
Hi @duncan-ncc ,

Thanks for the reply! It makes sense, and you are correct in the sense that if an attacker is able to replace the sysmon.exe with evil.exe on the sysvol share (which requires administrative privileges) then the compromised has already occurred.

I don't know if this is any better, but could there be any possible issues with crafting a Sysmon Windows Installer (.msi file) where the sysmon.exe and sysmon-config.xml are bundled in together?

This way you can create a simple GPO that installs the software package sysmon.msi on the workstations/servers. 

The only issue I see with deploying via .msi is that you require a system reboot on the endpoints and updating configuration files would be much slower.

Again, I dont know if this is a any better/easier. But let me know your thoughts on this!

**Comment by duncan-ncc** [comment]
Hi,

We did look at rolling Sysmon into an MSI format (especially for the SCCM deployment method) however this would require ourselves or the community to continually update the MSI with new Sysmon executable versions and config changes and at the moment it is a task that would be time consuming and take away from other development efforts.
