### ISSUE TITLE
Problem with dashboard import

### ISSUE THREAD

**Issue by Frippen71** [ukncsc/lme#72]
When I try to import dashboards v0.3.0.ndjson I only get an errormessage:

**Sorry, there was an error
The file could not be processed.**

If I try with dashboards v0.2.0.ndjson everything work as expected.
When I compare the files it looks like 0.3 are missing two lines at the top

I'm using ElasticSearch 7.8.1

Best regards
Fredrik

**Comment by a-d-a-m-b** [comment]
Hi @Frippen71.

Can you confirm that you have followed the steps in section 4.1.1 (where you find/replace your domain, including the trailing backslash)

https://github.com/ukncsc/lme/blob/master/docs/chapter4.md

**Comment by Frippen71** [comment]
Thank you for drawing my attention to that. I had missed that. Now it works. Thanks again!
