### ISSUE TITLE
deploy.sh hangs on waiting for elasticsearch to be ready

### ISSUE THREAD

**Issue by tomclewes** [ukncsc/lme#73]
**Describe the issue**
I am having issues getting this installed on a test server. When I run  deploy.sh it runs through, I answer the requested questions and then it gets to "Waiting for elasticsearch to be ready"

I have left this for an hour with no joy. I have flattened the VM and started again but again getting stuck on the same section.

Environment information:
Ubuntu 18.04.4 LTS
2vCPU
12GB RAM
50GB HDD
Proxy in environment = No

**To Reproduce**

******@****-log01:~$ sudo apt update
[sudo] password for ******:
Hit:1 http://gb.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://gb.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://gb.archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
111 packages can be upgraded. Run 'apt list --upgradable' to see them.
******@****-log01:~$ sudo apt install git -y
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to cor                                                                                                                                                                                               rect the problem.
******@****-log01:~$ sudo apt install git -y
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to cor                                                                                                                                                                                               rect the problem.
******@****-log01:~$ apt-get update
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denie                                                                                                                                                                                               d)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Pe                                                                                                                                                                                               rmission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13:                                                                                                                                                                                                Permission denied)
******@****-log01:~$ sudo su
root@****-log01:/****/******# apt-get update
Hit:1 http://gb.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://gb.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:4 http://gb.archive.ubuntu.com/ubuntu bionic-security InRelease
Reading package lists... Done
root@****-log01:/****/******# sudo apt install git -y
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to cor                                                                                                                                                                                               rect the problem.
root@****-log01:/****/******# sudo dpkg --configure -a
Setting up man-db (2.8.3-2ubuntu0.1) ...
Updating database of manual pages ...
root@****-log01:/****/******# sudo apt install git -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.17.1-1ubuntu0.7).
git set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 111 not upgraded.
root@****-log01:/****/******# sudo git clone https://github.com/ukncsc/lme                                                                                                                                                                                               .git /opt/lme/
Cloning into '/opt/lme'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 479 (delta 51), reused 80 (delta 27), pack-reused 358
Receiving objects: 100% (479/479), 5.05 MiB | 1007.00 KiB/s, done.
Resolving deltas: 100% (225/225), done.
root@****-log01:/****/******# cd /opt/lme/Chapter\ 3\ Files/
root@****-log01:/opt/lme/Chapter 3 Files# sudo ./deploy.sh install
[x] Installing prerequisites
Reading package lists...
Building dependency tree...
Reading state information...
net-tools is already the newest version (1.60+git20161116.90da8a0-1ubuntu1).
net-tools set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 111 not upgraded.
Enter the IP of this linux server: xxx.xxx.xx.xx.11
Enter the DNS name of this linux server, This needs to be resolvable from the Wi                                                                                                                                                                                               ndows Event Collector: ********
[x] Configuring winlogbeat config and certificates to use 192.168.**.** as the I                                                                                                                                                                                               P and ******.******.local as the DNS
This OS was detected as: ubuntu
[x] Configuring Auto Updates
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  bsd-mailx default-mta | mail-transport-agent needrestart
The following packages will be upgraded:
  unattended-upgrades
1 upgraded, 0 newly installed, 0 to remove and 110 not upgraded.
Need to get 41.7 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://gb.archive.ubuntu.com/ubuntu bionic-updates/main amd64 unattended-u                                                                                                                                                                                               pgrades all 1.1ubuntu1.18.04.14 [41.7 kB]
Fetched 41.7 kB in 0s (897 kB/s)
Preconfiguring packages ...
(Reading database ... 66996 files and directories currently installed.)
Preparing to unpack .../unattended-upgrades_1.1ubuntu1.18.04.14_all.deb ...
Unpacking unattended-upgrades (1.1ubuntu1.18.04.14) over (1.1ubuntu1.18.04.13) .                                                                                                                                                                                               ..
Setting up unattended-upgrades (1.1ubuntu1.18.04.14) ...
Replacing config file /etc/apt/apt.conf.d/50unattended-upgrades with new version
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.33) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
grep: grep: No such file or directory
grep: APT::Periodic::Update-Package-Lists "1";: No such file or directory
grep: grep: No such file or directory
grep: APT::Periodic::Unattended-Upgrade "1";: No such file or directory
grep: grep: No such file or directory
grep: APT::Periodic::Download-Upgradeable-Packages "1";: No such file or directo                                                                                                                                                                                               ry
This script will use self signed certificates for communication and encryption,                                                                                                                                                                                                Do you want to continue with self signed certificates? ([y]es/[n]o): y
[x] making root CA
Generating RSA private key, 4096 bit long modulus (2 primes)
................................................................................                                                                                                                                                                                               ................................................................................                                                                                                                                                                                               .............................................++++
................................................................................                                                                                                                                                                                               .............................................................++++
e is 65537 (0x010001)
Can't load /root/.rnd into RNG
140471919972800:error:2406F079:random number generator:RAND_load_file:Cannot ope                                                                                                                                                                                               n file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
[x] Signing root CA
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = Swarm
Getting Private key
[x] Making logstash Cert
Generating RSA private key, 4096 bit long modulus (2 primes)
....................................................................++++
..................................................++++
e is 65537 (0x010001)
Can't load /root/.rnd into RNG
140098003489216:error:2406F079:random number generator:RAND_load_file:Cannot ope                                                                                                                                                                                               n file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
[x] Signing logstash cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = ******.*********
Getting CA Private Key
[x] Making wlbclient Cert
Generating RSA private key, 4096 bit long modulus (2 primes)
................................................................................                                                                                                                                                                                               .........................++++
.........................................................++++
e is 65537 (0x010001)
Can't load /root/.rnd into RNG
140436276126144:error:2406F079:random number generator:RAND_load_file:Cannot ope                                                                                                                                                                                               n file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
[x] Signing wlbclient cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = wlbclient
Getting CA Private Key
[x] Making logstash Cert
Generating RSA private key, 4096 bit long modulus (2 primes)
................................................................................                                                                                                                                                                                               ........................................................................++++
................................................................++++
e is 65537 (0x010001)
Can't load /root/.rnd into RNG
140618921992640:error:2406F079:random number generator:RAND_load_file:Cannot ope                                                                                                                                                                                               n file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
[x] Sign elasticsearch cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = elasticsearch
Getting CA Private Key
[x] Making logstash Cert
Generating RSA private key, 4096 bit long modulus (2 primes)
.....++++
.......................................................++++
e is 65537 (0x010001)
Can't load /root/.rnd into RNG
140197543911872:error:2406F079:random number generator:RAND_load_file:Cannot ope                                                                                                                                                                                               n file:../crypto/rand/randfile.c:88:Filename=/root/.rnd
[x] Sign kibana cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = kibana
Getting CA Private Key
[x] Installing curl to get the docker convenience script
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libcurl4
The following packages will be upgraded:
  curl libcurl4
2 upgraded, 0 newly installed, 0 to remove and 108 not upgraded.
Need to get 0 B/373 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 66996 files and directories currently installed.)
Preparing to unpack .../curl_7.58.0-2ubuntu3.9_amd64.deb ...
Unpacking curl (7.58.0-2ubuntu3.9) over (7.58.0-2ubuntu3.8) ...
Preparing to unpack .../libcurl4_7.58.0-2ubuntu3.9_amd64.deb ...
Unpacking libcurl4:amd64 (7.58.0-2ubuntu3.9) over (7.58.0-2ubuntu3.8) ...
Setting up libcurl4:amd64 (7.58.0-2ubuntu3.9) ...
Setting up curl (7.58.0-2ubuntu3.9) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
[x] Installing docker
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
sh: 0: Can't open get-docker.sh
[x] Configuring docker swarm
./deploy.sh: line 325: docker: command not found
[x] Adding certificates and keys to Docker
./deploy.sh: line 249: docker: command not found
./deploy.sh: line 252: docker: command not found
./deploy.sh: line 253: docker: command not found
./deploy.sh: line 256: docker: command not found
./deploy.sh: line 257: docker: command not found
./deploy.sh: line 260: docker: command not found
./deploy.sh: line 261: docker: command not found
[x] Updating logstash configuration with logstash writer
[x] Creating custom logstash conf
./deploy.sh: line 268: docker: command not found
[x] Custom logstash config exists, Not creating
./deploy.sh: line 272: docker: command not found
./deploy.sh: line 275: docker: command not found
vm.max_map_count = 262144
./deploy.sh: line 329: docker: command not found
[x] Waiting for elasticsearch to be ready

**Expected behavior**
https://github.com/ukncsc/lme/blob/master/docs/chapter3-easy.md

**Screenshots**
Refer to **To Reproduce**

**Windows Event Collector (please complete the following information):**
N/A

**Linux Server (please complete the following information):**
 - Docker: Unknown as errors out before install
 - Docker compose stack file version: Unknown as errors out before install
 - Linux: Ubuntu 18.04.4 LTS
 - Logstash Version Unknown as errors out before install
 - Nginx config Unknown as errors out before install

**Additional context**

**Comment by a-d-a-m-b** [comment]
Hi @tomclewes 

It looks like the docker install hasn't worked. The install script is misleading you as it is polling docker logs for the elasticsearch container to come up, but docker isn't installed, and can't pull the image.

You can see this occurring in the log output that you provided.

`[x] Installing docker`
`curl: (77) error setting certificate verify locations:`
`CAfile: /etc/ssl/certs/ca-certificates.crt`
`CApath: /etc/ssl/certs`
`sh: 0: Can't open get-docker.sh`
`[x] Configuring docker swarm`
`./deploy.sh: line 325: docker: command not found`
`[x] Adding certificates and keys to Docker`
`./deploy.sh: line 249: docker: command not found`

This will need to resolved first

**Comment by tomclewes** [comment]
Thank you for coming back - Correct me if i'm wrong but doesn't Docker get instaleld as part of the install script?

**Comment by a-d-a-m-b** [comment]
Absolutely. It downloads the installer script and runs it (as per docker's guidance).

`curl -fsSL https://get.docker.com -o get-docker.sh > /dev/null`
`sh get-docker.sh > /dev/null`

The error above indicates that curl cannot download it, so it fails. 

`curl: (77) error setting certificate verify locations:`
`CAfile: /etc/ssl/certs/ca-certificates.crt`
`CApath: /etc/ssl/certs`

There seems to be some good advice as to how to resolve this issue on StackOverflow:
https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url/13400988#13400988

**Comment by tomclewes** [comment]
Happy to confirm that following the steps in the provided article resolved the issue.

> 
> 
> Absolutely. It downloads the installer script and runs it (as per docker's guidance).
> 
> `curl -fsSL https://get.docker.com -o get-docker.sh > /dev/null`
> `sh get-docker.sh > /dev/null`
> 
> The error above indicates that curl cannot download it, so it fails.
> 
> `curl: (77) error setting certificate verify locations:`
> `CAfile: /etc/ssl/certs/ca-certificates.crt`
> `CApath: /etc/ssl/certs`
> 
> There seems to be some good advice as to how to resolve this issue on StackOverflow:
> https://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url/13400988#13400988

Happy to confirm that following the steps in the provided article resolved the issue.
