### ISSUE TITLE
dashboards v0.3.0.ndjson hangs on import and then fails.

### ISSUE THREAD

**Issue by MichaelJKelly** [ukncsc/lme#74]
I am having issues getting this to import. I have used the convenience scripts to install LME. (Latest release as of 11/08/20)

Apart from replacing 'ChangeThisDomain' with my DNS information 'https://MyServer.Domain' (As instructed), I then import it and after a long time of hanging it eventually displays error stating this 'file can not be processed'. I have cloned from Git a number of times thinking potentially the file had corrupt in someway? Maybe a syntax error in the code? Not sure if anyone else has had this issue? 

Screenshot of error: https://imgur.com/a/FRCY1Kf

Environment information:
Ubuntu 18.04.4 LTS
2vCPU
12GB RAM
50GB HDD
Proxy in environment = No
Kibana 7.8.0
Elasticsearch 7.8.0
Logstash 7.8.0

Thanks

**Comment by a-d-a-m-b** [comment]
Hey @MichaelJKelly 

Can you confirm that when you do the find/replace steps as detailed in https://github.com/ukncsc/lme/blob/master/docs/chapter4.md you have included the trailing backslash in the domain?

**Comment by MichaelJKelly** [comment]
Hey @a-d-a-m-b 

Yes I can confirm that I have replaced 'ChangeThisDomain' with 'https://MyServer.Domain\'  (Including the backslash)

**Comment by MichaelJKelly** [comment]
Has anyone else had this issue? 

Potentially anything else i can try? 

Cheers

**Comment by MichaelJKelly** [comment]
Morning Guys,

As our team are looking to move to the latest LME release, apart from what was mentioned by @a-d-a-m-b are there any other fixes we can try to allow the dashboards templates to import for this latest version? Otherwise we will stick with the previous version.

Many thanks

**Comment by anderoo6** [comment]
Just updated from 0.2 to 0.3 and had the same issue, amongst others.

Using a backslash before each forward slash seems to have fixed it for me so instead of 'https://MyServer.Domain\' I used 'https:\\/\\/MyServer.Domain\'

**Comment by MichaelJKelly** [comment]
Hey @anderoo6,

Any chance you can post or upload the dashboard file for me to have a look at. Still not having any luck over here.

**Comment by anderoo6** [comment]
This is what mine looks like now:

`,\"params\":{\"parsedUrl\":{\"origin\":\"https:\/\/kibana.domain.local\",`

[dashboards v0.3.0upl.ndjson.txt](https://github.com/ukncsc/lme/files/5155630/dashboards.v0.3.0upl.ndjson.txt)

My initial problem was that the upgrade didn't apply properly and ES wasn't the right version for the dashboard.

If you run 'docker ps', note the container id for kibana,  then run 'docker logs' followed by the container id you should see the errors from the import. I was getting errors such as:

':"UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token \\ in JSON at position 2317\n    at JSON.parse (<anonre/server/saved_objects/routes/utils.js:33:19)'

**Comment by SimonAccordDS** [comment]
I had the same problem. I tried everything above but then I changed browser from Chrome to Firefox and it imported successfully in Firefox.

**Comment by a-d-a-m-b** [comment]
@MichaelJKelly & @anderoo6 ... was this resolved?

**Comment by MichaelJKelly** [comment]
@a-d-a-m-b 

Yes this was simply resolved for me by making the edit within Notepad++ which didn't introduce extra characters on saving the file, like it was when editing with regular notepad.

**Comment by a-d-a-m-b** [comment]
closing
