### ISSUE TITLE
[FeatureRequest] - Create LME 'appliance' for Hyper-V / VMWare once out of early development

### ISSUE THREAD

**Issue by tomclewes** [ukncsc/lme#75]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
For the LME solution (Linux VM) to be created into a downloadable 'Hardened appliance' for ease of deployment and ease of making security changes on the Linux VM and effectively stripping out the components of Linux which are not required.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by duncan-ncc** [comment]
Closed due to project archive
