### ISSUE TITLE
[BUG] Can't load /home/ubuntu/.rnd into RNG

### ISSUE THREAD

**Issue by Emohdee** [ukncsc/lme#78]
- New Ubuntu 18LTS install, no additions. 
- Followed steps as per install.
----- Deploy script shows this error when generating certs

# Can't load /home/ubuntu/.rnd into RNG

-----

Can't load /home/ubuntu/.rnd into RNG
140710227431872:error:2406F079:random number generator:RAND_load_file:Cannot open                                                                                                                             n file:../crypto/rand/randfile.c:88:Filename=/home/ubuntu/.rnd
[x] Sign elasticsearch cert
Signature ok
subject=C = GB, ST = UK, L = London, O = Docker, CN = elasticsearch
Getting CA Private Key
[x] Making logstash Cert
Generating RSA private key, 4096 bit long modulus (2 primes)

-----

Repeats for all 4.

Deploy not ran as root user. 

-----

# Resolution

sudo openssl rand -out /home/ubuntu/.rnd -hex 256

Opened bug as reference to assist others OR so that an additional check can be made on the install script.

**Comment by duncan-ncc** [comment]
Hello @Emohdee,

Thanks for this report, we have seen this on certain Ubuntu installs and will look to fix this in the next version

**Comment by adam-ncc** [comment]
Closing this issue as it does not block installation and the error appears to be with users' local OpenSSL configs in Ubuntu 18.04.:

https://github.com/openssl/openssl/issues/7754

The error can be safely ignored, and we've also added an extra output line during installation for the next version to make users aware that this will not block the installation. Thanks for bringing this to our attention.
