### ISSUE TITLE
Issue Subcriptions

### ISSUE THREAD

**Issue by nebblkshts** [ukncsc/lme#8]
I have run into a couple of issues. 

- I think I have the Collector set up because it shows up in subscriptions. I can not get other PCs to subscribe. I verified the GPO is processing with no errors. What did I miss?

- The second thing is the Schedule Task GPO link is not right it takes you back the "Chapter 1" GPOs. I tried to create it on my own and not sure it is working either. But one step at a time.

**Comment by kamouchka** [comment]
I ran into the same problem after setting up the subscription in chapter 2 on a Windows 2019 server .
The winrm service was not listening correctly on TCP 5985 and none of my source computers showed up in the subscription.

Noticed these two errors in the system's Windows/System event log after starting the winrm service.
![image](https://user-images.githubusercontent.com/50121113/56928042-96104780-6acd-11e9-8369-27eabdfdb5c4.png)
![image](https://user-images.githubusercontent.com/50121113/56928080-b04a2580-6acd-11e9-8cd2-87a1c5c8001d.png)

Solved the issue by manually deleting and creating the binding with a different SDDL as outlined [here](https://support.logbinder.com/SuperchargerKB/50145/All-subscriptions-have-0-active-forwarders-System-Event-IDs-10128-10129).

Your second request [has already been resolved](https://github.com/ukncsc/lme/pull/3).

**Comment by duncan-ncc** [comment]
@kamouchka Thanks, This is the kind of community support I enjoy seeing! 
In regards to the URL ACL issues this was experienced during our testing on specific configurations and Microsoft have issued guidance for this [here](https://support.microsoft.com/en-in/help/4494462/events-not-forwarded-if-the-collector-runs-windows-server-2019-or-2016).
