### ISSUE TITLE
Cannot import saved object

### ISSUE THREAD

**Issue by SimonJohnG** [ukncsc/lme#81]
Import saved object failed when uploading dashboard v0.3.0.ndjson. File modified with correct server details. Sorry, there was and error, the file could not be processed

**Comment by duncan-ncc** [comment]
Hello Simon,

Have you tried the steps in #74 ?

Thanks,

**Comment by SimonJohnG** [comment]
Successfully imported.

Just no data ☹

**Comment by duncan-ncc** [comment]
Hello Simon,

Have you followed the checklists at the end of the chapters?

Are logs making it to the windows event collector, has winlogbeat connected succesfully to logtstash etc.

**Comment by a-d-a-m-b** [comment]
closing this ticket, as the import issue was fixed by following the steps in #74
