### ISSUE TITLE
Data all of a sudden stopped logging into LME

### ISSUE THREAD

**Issue by Sommie99** [ukncsc/lme#84]
All LME data suddenly stopped being reported in LME.

I am not a linux expert, yet LME was previously working (before a windows server update)

I have checked and the winbeat logs on the windows box and they seem to suggest they are being published.

Where should i be checking on the linux box to see if they are being stored on the linux box?

Kind regards

**Comment by 1n6w3coza** [comment]
Hi, have you seen this and eliminated it as a cause?

https://github.com/ukncsc/lme/issues/60

**Comment by Sommie99** [comment]
Many thanks, I will check this out and let you know how i get on

**Comment by Sommie99** [comment]
Many thanks for your help, this link helped a lot.  Below is a summary of what i did

I ended up running:

docker service logs lme_logstash --tail 20 --timestamps

i got the following as part of my error

 "reason"=>"Validation Failed: 1: this action would add [4] total shards, but this cluster currently has [1000]/[1000] maximum shards open;"}}}}

the max shards were max'd out as we are running over 120 servers to the database

To double the number of shards to 2000 i opened LME dashboard, went to the dev tools, then typed the following into the console

PUT /_cluster/settings
{
  "persistent": {
      "cluster.max_shards_per_node": "2000"
  }
}
