### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by flipperflopper24** [ukncsc/lme#85]
Hi, Just after what maybe a quick solution - i need to setup Packetbeat but the certs I'm using suggest they have been generated only for 127.0.0.1 - i dont want to mess my current install up - is there a easy way to locate the server Certs ?

Many Thankos

**Comment by duncan-ncc** [comment]
Hello,

The certificates are located in /opt/lme/Chapter 3 Files/certs/ on a standard install.
The elasticsearch server has the cert DNS of elasticsearch and ip of 127.0.0.1 by default (as its only spoken to in a typical LME install by logstash)

**Comment by a-d-a-m-b** [comment]
Hi @flipperflopper24 - did you get this resolved?

**Comment by flipperflopper24** [comment]
No. We ended up using another system for syslog. Would be good to have the
logs from our devices into LME thou. Syslog that is. Thanks

**Comment by duncan-ncc** [comment]
Hi @flipperflopper24, Thank you for your update, We do hope to support syslog officially in the future (there is actually a listener on 12514 for syslog but it is not documented at the moment) 

As your issue is resolved I am going to close this issue.
