### ISSUE TITLE
Services doesn't restart after a reboot ubuntu 20.04

### ISSUE THREAD

**Issue by richardbrn** [ukncsc/lme#86]
**Describe the issue**
I have installed the system and on the Ubuntu server ran the deploy.sh
Everything was working okay and I could browse to Elastic web server and see details of users and computers exactly as it should be working

The server has rebooted after an upgrade and now I can't access the elastic/kabana web site - It looks like the services have stopped but when I list the services there isn't anything that matches lme, kabana or similar to restart.

Any help appreciated

**Comment by duncan-ncc** [comment]
Hello,

As per the [prerequisites page](https://github.com/ukncsc/lme/blob/master/docs/prerequisites.md ) We have not tested the deploy script on 20.04.

LME doesn't run as a service, Instead it is a collection of docker images, Have you checked to see if the docker service is running and what the containers show as if you run ```docker stack ps lme``` ? 

Thanks,
Duncan

**Comment by richardbrn** [comment]
It is working again this morning - the docker stack ps lme shows everything is up.
I wonder if it just takes  long time to start up after a reboot and I've not noticed before...

**Comment by richardbrn** [comment]
After another reboot to test it hasn't started again so now timing to see if it does.   22 minutes so far.
What I have noticed is that docker stack ps lme shows...


richardbrumpton@inf-wecdb:~$ sudo docker stack ps lme
ID                  NAME                  IMAGE                                                 NODE                DESIRED STATE       CURRENT STATE            ERROR                              PORTS
jdli3690c7ku        lme_elasticsearch.1   docker.elastic.co/elasticsearch/elasticsearch:7.8.0   inf-wecdb           Running             Running 14 minutes ago
tetfyjkvwupp        lme_logstash.1        docker.elastic.co/logstash/logstash:7.8.0             inf-wecdb           Running             Running 14 minutes ago
2mmkkm2dia3d        lme_kibana.1          docker.elastic.co/kibana/kibana:7.8.0                 inf-wecdb           Running             Running 14 minutes ago
0j0cxhn31lin        lme_elasticsearch.1   docker.elastic.co/elasticsearch/elasticsearch:7.8.0   inf-wecdb           Shutdown            Failed 14 minutes ago    "No such container: lme_elasti…"
fg0eed1rdcjb        lme_logstash.1        docker.elastic.co/logstash/logstash:7.8.0             inf-wecdb           Shutdown            Failed 14 minutes ago    "No such container: lme_logsta…"
v73tfbdfg4be        lme_kibana.1          docker.elastic.co/kibana/kibana:7.8.0                 inf-wecdb           Shutdown            Failed 14 minutes ago    "No such container: lme_kibana…"
richardbrumpton@inf-wecdb:~$

So two of each with 3 running and three showing shutdown and failed...
