### ISSUE TITLE
Configure Docker proxy settings during install

### ISSUE THREAD

**Issue by davidminty** [ukncsc/lme#88]
**Problem**
If the ELK stack is being deployed behind a web proxy, and Docker isn't configured to use the proxy, the deploy script can hang at "[x] Waiting for elasticsearch to be ready". In the background, docker is unable to pull the images from docker.elastic.co and the containers continually error out.

**Solution**
As described here: https://docs.docker.com/config/daemon/systemd/#httphttps-proxy, the docker service must be configured with Environment variables for http_proxy and https_proxy. To resolve this, the deploy script will need to do the following:

- Create directory "/etc/systemd/system/docker.service.d" (and all necessary parent directories)
- Get the web proxy address, from the system wide env variables HTTP_PROXY and HTTPS_PROXY and/or user input during the script
- Create file "/etc/systemd/system/docker.service.d/http-proxy.conf" and append the proxy settings in the below format:
```
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:80"
Environment="HTTPS_PROXY=https://proxy.example.com:443"
```
- Reload the service daemon
`sudo systemctl daemon-reload`

In my test, I created these files before running the deploy script and it completed with no errors, so these steps are best added BEFORE installing/configuring Docker.

**Comment by a-d-a-m-b** [comment]
Hi David. Thanks for the issue - this is something that we will be included as part of the next version of the documentation. I'll leave this task/issue open until that goes live.

If you would like to add these instructions before then, we will certainly accept pull request! Thanks

**Comment by davidminty** [comment]
Thanks Adam.

Created PR #89 with instructions on how to do this manually added to Chapter 3 docs.

**Comment by a-d-a-m-b** [comment]
closing this issue as the changes have been made into the master branch under PR 89
