### ISSUE TITLE
[QUESTION] Disk space requirements

### ISSUE THREAD

**Issue by kamouchka** [ukncsc/lme#9]
What are your experiences with disk space requirements with LME?
You are not mentioning disk space in the [requirements section](https://github.com/ukncsc/lme/blob/master/docs/prerequisites.md#required-infrastructure).

I set up a test environment (1TB HDD for the Linux server) and enrolled one single Windows 10 workstation to the LME system.
Within 5 hours of logging the size of the Forwarded events log on the Windows event collector grew to 20MB. 

We have around 200 Windows workstations and servers I would like to enroll at some point.
Also Cyber Essentials requires a log retention of at least 3 months.

I understand that all environments and systems are different and it is hard to give exact number. Nevertheless, a sizing guide with some rough estimations would be useful.

**Comment by duncan-ncc** [comment]
@kamouchka Thanks for your feedback, We avoided putting disk space requirements in as we acknowledge everyones available capacity on different infrastructures will be different but I will look into adding some baseline example data rates from our development environment and our trial clients.

The windows event collector configuration is set to collect application errors and Microsoft AppLocker and with sysmon sometimes application launches can cause bloat but it would be interesting to get feedback on what proportions of the different types of logs you are receiving.

We are aiming to find a good level of logging to avoid having to frequent roll overs of logs when using a sensible size of disk.

**Comment by shane-m1** [comment]
Just to add, we are considering looking to help users ‘tune’ their config to reduce heavily repeated logs (which will change per installation and software installed), but it’s quite advanced to left it out of the initial release. 

For now, try the setup on a small selection of machines and roll out once you’ve got a sample of mb/day/client.

**Comment by kamouchka** [comment]
Waited for the [dashboards getting fixed](https://github.com/ukncsc/lme/issues/6) before further looking into it. Thanks for jumping on that so quickly @duncan-ncc 

I finally figured out the root cause. 
Thought I will post what I did as others might benefit from my experience and my troubleshooting steps.

The single machine I enrolled created over 60k events per day requiring about 2.5 GB of disk space for only a week worth of logs.
![EventNumber](https://user-images.githubusercontent.com/50121113/57111441-fa344500-6d33-11e9-9434-73bd0bac629c.PNG)

As suggested by @duncan-ncc I looked into the event source and Sysmon clearly stood out here.
![image](https://user-images.githubusercontent.com/50121113/57193151-18669480-6f30-11e9-97d9-ea2c34f77c3e.png)

Looking deeper into it, most of the events were SYSMON EVENT ID 3 : NETWORK CONNECTION INITIATED
![image](https://user-images.githubusercontent.com/50121113/57193219-a773ac80-6f30-11e9-881d-dd2e1d04532a.png)

I finally found the culprit when looking for the applications responsible for all the events. Chrome, Spotify, etc..
![image](https://user-images.githubusercontent.com/50121113/57193375-39c88000-6f32-11e9-98ab-d2cd9dcc04a3.png)

I thought I can simply exclude Chrome from the [Syslog config](https://github.com/SwiftOnSecurity/sysmon-config/blob/master/sysmonconfig-export.xml). 
However, I discovered that there is already an exclusion for Spotify configured which didn't seem to have any affect looking at all the Spotify events I was getting.

So it seems that the Sysmon config file was never used at all and the Sysmon simply captured ALL events without any filtering.
I then manually restarted sysmon feeding it the config file.
`C:\Windows\sysmon>Sysmon64.exe -c sysmon.xml`
Immediately only the correct events were logged.

Troubleshooting [update.bat](https://github.com/ukncsc/lme/blob/master/Chapter%202%20Files/GPO%20Deployment/update.bat) I discovered, that sigcheck64.exe was not in the expected location, causing all the issues with the config not being applied.
`SET GLBSIGCHECK=\\%FQDN%\sysvol\%FQDN%\Sysmon\%SIGCHECK%`


My conclusions:
1. Despite fine tuning not being the root cause for my issue in the end, providing some guidelines for drilling into events with Kabana (had no experience with it before) and how to optimize the Sysmon config will be indeed useful for users once they are more familiar with single components. 

2. Troubleshooting the Sysmon install script [update.bat](https://github.com/ukncsc/lme/blob/master/Chapter%202%20Files/GPO%20Deployment/update.bat) is quite painful. 
In fact, I haven't found a way to run/test the script under the same conditions as the schedule task would run it. Just ended up changing the scheduled task's execution time within the GPO repeatedly to trigger an execution. Furthermore I had to heavily change the script to make it generate useful debugging information.
Might also be useful to add an additional item to the checklist in [chapter 2](https://github.com/ukncsc/lme/blob/master/docs/chapter2.md#chapter-2---checklist) to ensure that Sysmon is actually running with the correct config.
